<?php
$email=<<< email
Dear {$firstName} {$lastName},

You have not verified your e-mail. Click on the following link to complete the registration process and avail the privileges
you are yet not aware of.

{$verifyUrl}

If you are having problems clicking on the link, copy-paste it in your browser
to verify your account.
Questions? Comments? Contact us at contact@wethementors.com

Thanks and Regards,
Admin
www.wethementors.com
email;
?>