<?php
$email=<<< email
Mentors
Hi {$firstName} {$lastName},

We have added some important/guess questions for ISC Computer Practical {$year}.
All the questions have been designed keeping in mind the pattern of questions that had been asked in previous ISC
Computer Practicals.
The questions are complete with solutions and documentations. You are advised to read the question carefully
before peeking into the solution. Though we have made all efforts to ensure that all the solutions are correct yet if
something doesn't work as expected you are welcome to post your queries at http://www.wethementors.com/qa/ask-question.

You can access the list of computer practical questions at http://www.wethementors.com/isc/isc-computer-practical?v=guess-questions.

Questions? Comments? Contact us at registration@wethementors.com
Thanks and Regards,
Admin
http://www.wethementors.com
This message was sent to {$emailUser}
	If you don't want to receive such emails from wethementors.com in the future, please send an email
	to admin@wethementors.com.
email;
?>