<?php
$email=<<< email
Mentors
Hi {$firstName} {$lastName},
It's long since you've visited wethementors.com. See what you missed.


Java Quiz
Java Quiz designed especially for young minds who wish to test their mettle in programming.
	The three different levels:
Beginner
Intermediate
Advanced
cater to different levels of understanding and knowledge.
	Check it out now! (http://www.wethementors.com/fun/java-quiz)
	
	
Persons of Eminence
Learn about people who made a difference to the world. It is the life story of people who made their
	way to the top in their respective fields by not giving up at the last moment.
	http://www.wethementors.com/resources/people (Read about these inspirational people).
Forum (http://www.wethementors.com/forum)
The forum is designed just for the inquisitive minds. You don't get an anser anywhere, post it here.
	We promise to deliver you the best of answers to your queries.
It is the unquenched mind that leads the race.
	http://www.wethementors.com/forum (Ask a question now).
	
	
Exam Essentials
We do strive hard to provide students with the best of examination papers.
	Our repository is continuously increasing with quality mock papers, sample papers, previous years'
	exam papers etc.
Check out the resources for:
	Class X (http://www.wethementors.com/icse)
	Class XII (http://www.wethementors.com/isc)

Riddles
It's always fun to riddle with your friends. Make sure you don't go riddled by your friends without a
	counter riddle. We have gathered a vast repository of riddles just for you.
Start riddling (http://www.wethementors.com/fun/riddles)

Doodle
Ever wanted to bring your inner artist on to the canvas?Doodle lets you draw your imagination on canvas.
	Sometimes there is a strong urge to sketch things out of our mind on canvas; fragments of a dream,
	figments of imagination or complete nonsense.If you feel that way, let's 
Doodle (http://www.wethementors.com/doodle)

Questions? Comments? Contact us at registration@wethementors.com
Thanks and Regards,
Admin
http://www.wethementors.com
This message was sent to {$emailUser}
	If you don't want to receive such emails from wethementors.com in the future, please send an email
	to admin@wethementors.com.
email;
?>