<?php
$email=<<< email
Dear {$result->first_name},

We received a request for the password associated
with this email address {$result->email} on www.wethementors.com
to be reset.

If you did not make this request, delete this message. Your password won't be reset
until you click on the following link.

Reset Password link:{$verifyUrl}

If you are having problems clicking on the link, copy-paste it in your browser
to reset your password.
Questions? Comments? Contact us at contact@wethementors.com

Thanks and Regards,
Admin
Wethementors
email;
?>