<?php
$htmlbody=<<< email
<html>
<body>
  <h2>Password Recovery</h2>
  <blockquote>
	<h3>Dear {$result->first_name},</h3>
	<p>We received a request for the password associated
with this email address <b><a>{$result->email}</a></b> on <a href='http://www.wethementors.com'>www.wethementors.com</a>
to be reset.</p>
  </blockquote>
  <blockquote>
  If you did not make this request, delete this message. Your password won't be reset
until you click on the following link.
  </blockquote>
  <blockquote>
<p>Reset Password link:{$verifyUrl}</p>
  </blockquote>
  <p>If you are having problems clicking on the link, copy-paste it in your browser
  to reset your password.</p>
<p> Questions? Comments? Contact us at <a>contact@wethementors.com</a></p>
<br />
<h3>Thanks and Regards,</h3>
<h4>Admin<br />
<a href='http://www.wethementors.com'>www.wethementors.com</a>
</h4>
</body>
</html>
email;
?>