<?php if($this->pageCount){ ?>
<!---->
<!---->
<?php if($this->first!=$this->current){  ?>
    <a class="btn btn-xs btn-primary" href="?page=<?php echo $this->first;?>">first</a>
    <?php } ?>
<!-- ADD PREVIOUS BUTTON -->
<?php if(isset($this->previous)){  ?>
    <a class="btn btn-xs btn-primary" href="?page=<?php echo $this->previous; ?>">&lt;previous </a>
    <?php } ?>
<!-- SHOW THE AVAILABLE PAGES -->
<?php
    if($this->pageCount > 5){
        foreach($this->pagesInRange as $page){
            if($page!=$this->current){ ?>
            <a href="?page=<?php echo $page; ?>"><?php echo $page;?></a>
            <?php }else{?>
            <?php echo $this->current;?>
            <?php }
        }
    }?>
<!-- ADD NEXT BUTTON -->
<?php
    if(isset($this->next)){
        ?>
    <a class="btn btn-xs btn-primary" href="?page=<?php echo $this->next;?>"> next&gt;</a>
    <?php }?>
<?php if($this->last!=$this->current && $this->next!=$this->last){  ?>
    <a class="btn btn-xs btn-primary" href="?page=<?php echo $this->last;?>">last</a>
    <?php } ?>



<?php
}
?>