<?php
//	$title = isset($this->subject)?$this->subject:'Page not found';
	$this->headTitle()->set($this->subject." Notes");
	echo $this->headTitle();
?>
<div class="topic-container">

	<div id="tutorials" class="content bg tuts">

		<div class="header">
			<h1><?php echo $this->subject; ?></h1> <hr />
		</div>

		<div class="notes-list subjects">

			<?php if(isset($this->paginator)): ?>

				<?php foreach($this->paginator as $index => $note): ?>
					<?php
						if($index % 2 == 1){
	//						$imgClass = ' col-sm-push-8';
	//						$contentClass = ' col-sm-pull-4';
	//						$direction = ' right';
						}else{
							$imgClass = $contentClass = '';
							$direction = ' left';
						}
						if($note['category'] == 'people'){
							$link = $this->baseUrl('people/'.$note['slug']);
						}else{
							$link = $this->baseUrl('notes/'.strtolower(str_replace(" ", "-", $note['category'])).'/'.$note['slug']);
						}
					?>
						<div class="notes_unit<?php echo $direction; ?>">
							<h2><?php echo $note['heading']; ?></h2>
							<div class="clearfix">
								<div class="note_image text-center col-sm-4<?php echo $imgClass; ?>">
									<img class="img-thumbnail" src="<?php echo $this->baseUrl('/images/content/uploads/'.$note['cover_image']); ?>" alt="<?php echo ucwords($note['heading']); ?> Notes" />
								</div>
								<div class="note_content col-sm-8<?php echo $contentClass; ?>">
									<p>
										<?php echo $note['extract']; ?>
									</p>
									<a class="btn btn-xs btn-default"
									   href="<?php echo $link; ?>">
										Read More
									</a>
								</div>
							</div>
							<hr />
						</div>
				<?php endforeach ?>
				<div id="pagination" class="pagination text-center">
					<?php echo $this->paginationControl($this->paginator,
						'Jumping',
						'includes/paginationcontrol.phtml');
					?>
				</div>
			<?php else: ?>
				<div class="alert alert-info">
					<p>No notes for this subject so far. Please check back soon.</p>
				</div>
			<?php endif; ?>

		</div><!--notes-list-->

	</div><!--tutorials-->

</div><!--topic-container-->