<!DOCTYPE html>
	<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta property="og:title" content="Doodle" />
	<meta property="og:type" content="activity" />
	<meta property="og:url" content="http://www.wethementors.com/doodle" />
	<meta property="og:image" content="http://www.wethementors.com/images/doodle.png" />
	<meta property="og:site_name" content="wethementors" />
	<meta property="fb:admins" content="828098119"/>
	<title>Doodle - Imagination on canvas</title>
	<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/scripts/subjects.js"></script>
	<script src="<?php echo $this->baseUrl()?>/scripts/jscolor/jscolor.js"></script>
	<script src="<?php echo $this->baseUrl()?>/scripts/js/modernizr.custom.34982.js"></script>
	<script src="<?php echo $this->baseUrl()?>/scripts/js/sketcher.js"></script>
	<link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl()?>/skins/blues/css/doodle.css">
	<link href='http://fonts.googleapis.com/css?family=The+Girl+Next+Door' rel='stylesheet' type='text/css'>
	<script type="text/javascript">
var sketcher = null;
$(document).ready(function(e) {
	sketcher = new Sketcher( "fbCover", "000" );
	sketcher.updateGradient();
	sketcher.updateFont();
});
</script>
	</head>
	<body>
<?php include_once('analyticstracking.php'); ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=164479910348651";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="facebookCover">
	<h1>Create a doodle</h1>
	<canvas id="fbCover" width="760" height="313">
	<p>Sorry your browser does not support canvas!</p>
	<p>Please upgrade to any of the following browsers to use facebook-cover:</p>
	<ul>
		<li>IE 9.0</li>
		<li>Firefox 12.0</li>
		<li>Chrome 19.0</li>
		<li>Safari 5.1</li>
		<li>Opera 11.6</li>
	</ul>
	</canvas>
<form id="toolsForm">
 <table id="toolbox">
	<tr>
		<th><label for="color">Background Color:</label></th>
	<td><input id="color" class="color" onchange="color1=this.color.toString(); sketcher.updateGradient();" value="EA3D8E" size="5"  /></td>
<th><label for="colorFont">Text Color:</label></th>
<td><input id="colorFont" class="color" onchange="color1=this.color.toString(); sketcher.updateFont();" value="84ED6F" size="5" /></td>
<th><label for="colorBrush">Brush Color:</label></th>
<td><input id="colorBrush" class="color" onchange="color1=this.color.toString(); sketcher.brushColor(); " value="000" size="5" /></td>
<th><label for="brushSize">Brush Size:</label></th>
	<td><select id="brushSize" autocomplete="off" onchange="sketcher.brushColor();"><option value="small-x" selected="selected">Small-x</option><option value="small-xx">Small-xx</option><option value="medium-x">Medium-x</option><option value="medium-xx">Medium-xx</option><option value="big-x">Big-x</option><option value="big-xx">Big-xx</option></select></td>
<th><label for="eraser">Eraser:</label></th>
<td><input type="checkbox" name="eraser" id="eraser" autocomplete="off" onclick=" sketcher.eraseIt();" /></td>
	</tr>
<tr>
	<th><label for="shape">Shape:</label></th>
	<td><select id="shape"  autocomplete="off"><option value="none" >Neither</option><option value="dots" selected="selected">Dots</option><option value="circles">Circles</option><option value="squares">Squares</option></select></td>
	<th><label for="shapeColor">Shape Color:</label></th>
	<td><input id="shapeColor" class="color" onchange="color1=this.color.toString(); sketcher.previewHandler(); " value="D7DB65" size="5" /></td>
<td id="prev"><input type="button" id="previewButton" value="Preview" onclick=" sketcher.previewHandler(); " /></td>
<td><input type="button" value="Clear"	onclick="sketcher.clear();" />
</td>
<td><input type="button" value="Save" onclick="sketcher.save();" />
</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
 </table>
</form>
<div id="ads">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-1662490668144398";
/* doodle-fb */
google_ad_slot = "7616414125";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-1662490668144398";
/* papers- horizontal medium */
google_ad_slot = "8174382668";
google_ad_width = 468;
google_ad_height = 15;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
 <div id="socials">
<div class="fb-like" data-href="http://www.wethementors.com/doodle" data-send="false" data-width="450" data-show-faces="true"></div>
<div class="fb-comments" data-href="http://www.wethementors.com/doodle" data-num-posts="10" data-width="700"></div>
 </div>
</div>
	</body>
</html>