<?php $this->headTitle()->set('Chemistry Advanced Quiz');
echo $this->headTitle();
?>
<script type="text/javascript">
    $("html").bind("mouseleave", function(event){
        alert("You cannot leave the quiz halfway.");
        location.reload();
    });
</script>
<noscript>
    <style type="text/css">
        .content{
            visibility: hidden;
        }
    </style>
</noscript>
<div class="content quiz">
    <link  href="<?php echo $this->baseUrl();?>/skins/reds/css/quiz.css" media="screen" rel="stylesheet" type="text/css" >
    <div id="quiz_container" class="col-md-9 col-lg-8 acronym">
        <h1 class="text-center">The Advanced Chemistry Quiz</h1>
        <p class="text-center">Choose the correct option for each of the acronym given below. <br />
            Do not leave the quiz area before submitting your answers else the quiz will reset.
        </p>
        <div id="quiz_form">
            <?php echo $this->form;?>
        </div>
    </div>
    <div class="col-md-3 col-lg-4 text-right">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
        <br />
        <br />
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
    </div>
</div>