<?php
$this->headTitle()->set('This page is under construction');
echo $this->headTitle();
?>

<style type="text/css">
	#auth {
		border: 1px solid #ddd;
		border-radius: 1ex;
		margin: 50px auto;
		max-width: 768px;
		padding: 20px 50px;
	}
	#auth h1 {
		text-align: center;
	}
	#auth p {
		font-size: 1.3em;
		padding: 5px;
	}
	#auth ul {
		margin: 20px 0 20px 40px;
	}
	#auth li {
		font-size: 18px;
	}
</style>

<div class="content">
	<div class="content bg-warning " id="auth">
		<h1 class="text-danger">This page is under construction.</h1><br />
		<h3>Please be patient! We're working on some awesome content.</h3>
	</div>
</div>