<?php //echo $this->doctype();?>
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/Organization">
<head>
<meta itemprop="name" content="Mentors - Providing education assistance to inquisitive minds.">
<meta itemprop="description" content="Find sample papers, guess papers, programming tutorials in Java, previous years' solved papers, quiz, riddles, doodle, forum, profile option and much more.">
<meta itemprop="image" content="http://www.wethementors.com/images/heading.png">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="Mentors is a coaching institute for classes IX to XII." />
<meta name="keywords" content="mentors,wethementors,programming,ISC,ICSE,java,guess,important,
PCM,computer applications,english,literature,10,12,computer coaching,
java coaching,programs,board questions,sample papers Tv3Z6pvVcAnZqkEb6AQvjjneOgs" />
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
<link rel="icon" href="<?php echo $this->baseUrl();?>/images/logo.ico" type="image/icon" />
    <?php
    echo $this->headTitle();
	$this->headScript()->appendFile($this->baseUrl().'/scripts/thirdparty/jquery/jquery-1.11.1.min.js');
	$this->headScript()->appendFile($this->baseUrl().'/scripts/bootstrap.min.js');
    $this->headLink()->appendStylesheet($this->baseUrl().'/skins/common/css/bootstrap.min.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/skins/common/css/bootstrap-responsive.min.css');
//	$this->headLink()->appendStylesheet($this->baseUrl().'/skins/greens/css/fo-bizarre-min.css');
	$this->headLink()->appendStylesheet($this->baseUrl().'/skins/greens/css/responsive-biz.css');
?>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    echo $this->headLink();
	echo $this->headScript();
?>
</head>
    <body>
        <div id="One2ka4"></div>

        <div id="page" class="container-fluid">
            <?php require_once APPLICATION_PATH.'/../layouts/templates/userInfo.php'; ?>
            <?php require_once APPLICATION_PATH.'/../layouts/templates/admin_header.php'; ?>
             <div id="contentWrapper" class="row-fluid">
                <div id="main" class="col-sm-8 col-lg-9">
                  <?php echo $this->layout()->content; ?>&nbsp;
                </div>
                <div id="sidebar_right" class="col-sm-4 col-lg-3"></div>
             </div>
        </div>

        <div id="Two4ka1">
              <div id="copyright">
              <span><?php
              $pp=$this->url(array('controller'=>'home', 'action'=>'privacy-policy'),null,true);
              $tou=$this->url(array('controller'=>'home', 'action'=>'terms-of-use'),null,true);?>
              &copy;<?php echo strftime("%Y", time()); ?> Mentors. All Rights Reserved.
              <a href="<?php echo $pp;?>">Privacy Policy</a> and <a href="<?php echo $tou;?>">Terms of Use</a>
              </span><br />
              <span><script type="text/javascript">document.write(Date());</script>
              </span>
              </div>
        </div>
    </body>
</html>