<?php echo $this->doctype();?>
<html itemscope itemtype="http://schema.org/Organization">
<head>
<meta itemprop="name" content="Mentors - Providing education assistance to young minds.">
<meta itemprop="description" content="Find sample papers, guess papers, programming tutorials in Java, solved ISC computer papers, quiz, riddles, doodle, forum.">
<meta itemprop="image" content="http://www.wethementors.com/images/heading.png">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="Mentors - Providing education assistance to young minds." />
<meta name="keywords" content="solved java programs, java quiz,mentors,wethementors,java programming,ISC,ICSE,java,guess,important,
PCM,computer applications,quiz,forum,riddles,english,literature,10,12,programs,exam questions,sample papers Tv3Z6pvVcAnZqkEb6AQvjjneOgs" />
<meta name="wot-verification" content="156d048a2c5f360c06c6"/>
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<link rel="icon" href="<?php echo $this->baseUrl();?>/images/logo.ico" type="image/icon" />

    <?php
        echo $this->headTitle();
        $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js');
        $this->headScript()->appendFile($this->baseUrl()."/scripts/home.js");
        $this->headLink()->appendStylesheet($this->baseUrl().'/skins/blues/css/bootstrap.min.css');
        $this->headLink()->appendStylesheet($this->baseUrl().'/skins/reds/css/hidden-style-min.css');
    ?>
<?php echo $this->headScript(); echo $this->headLink();?>
<?php

    $mdlUser=new Model_User();
	if (Zend_Auth::getInstance()->hasIdentity()) {
		$identity = Zend_Auth::getInstance()->getIdentity();
		$username=$identity->username;
		$toId=$mdlUser->getIdByEmail($identity->email);
		$mdlMessages=new Model_Messages();
		$messages=$mdlMessages->countUnreadMessages($toId);
	}else{
		  $username = "";
		  $identity="";
		  }
    ?>
</head>
<body>
<div id="fb-root"></div>
<div id="One2ka4"></div>
<div id="page">
    <div id="header">
        <div id="topbar">
            <div id="links" class="clearfix">
                <?php
                $home=$this->url(array('module'=>'','controller'=>'home', 'action'=>'index'), null,true);
                $contact=$this->url(array('controller'=>'home', 'action'=>'contact'), null,true);
                $search=$this->url(array('controller'=>'home', 'action'=>'search'), null,true);
                $login=$this->url(array('controller'=>'user', 'action'=>'login'), null,true);
                $logout=$this->url(array('controller'=>'user', 'action'=>'logout'), null,true);
                $register=$this->url(array('controller'=>'user', 'action'=>'register'), null,true);
                $profile=$this->url(array('controller'=>'profile', 'action'=>'index', 'user'=>$username), null,true);
                $inbox=$this->url(array('controller'=>'profile', 'action'=>'messages'), null,true);
                ?>
                <div class="pull-left">
                    <span><a href='<?php echo $home;?>'>Home </a>| </span>
    <!--                <span><a href='--><?php //echo $contact;?><!--'>Contact </a>| </span>-->
                    <span><a href='<?php echo $search;?>'>Search </a> </span>
                </div>
                <?php if (!$identity) { ?>
                <div class="pull-right"><a href="<?php echo $register;?>">Register</a> | <a href="<?php echo $login; ?>">Login</a></div>
                <?php } else { ?>
                <div class="pull-right">
                    <a href="<?php echo $profile; ?>"><?php echo $username; ?></a>  |
    <!--                <a href="--><?php //echo $inbox; ?><!--">Messages<span class="prominent">--><?php //echo isset($messages)?$messages:""?><!--</span></a> |-->
                    <a href="<?php echo $logout; ?>">Logout</a>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
	<div id="logobar">
	  <div id="banner-ad">
			<script type="text/javascript"><!--
				  google_ad_client = "ca-pub-1662490668144398";
				  /* doodle-fb */
				  google_ad_slot = "7616414125";
				  google_ad_width = 728;
				  google_ad_height = 90;
				  //-->
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
	  </div>
		<div id="logo"><a href="<?php echo $home;?>"><img src="<?php echo $this->baseUrl();?>/images/heading.png" alt="Mentors - We Change The Way You Think" /></a></div>
	</div>
	<div id="menu_holder">
	  <div id="menu">
<?php
	  $sitemap=$this->url(array('controller'=>'Home', 'action'=>'sitemap'),null,true);
	  
	  $tutorials=$this->url(array('controller'=>'resources', 'action'=>'tutorials'),null,true);
	  $poi=$this->url(array('controller'=>'resources','action'=>'people'),null,true);
	  $ant=$this->url(array('controller'=>'resources','action'=>'installing-ant'),null,true);

	  $x_sample_papers=$this->url(array('controller'=>'icse', 'action'=>'sample-papers'),null,true);
	  $x_syllabus=$this->url(array('controller'=>'icse', 'action'=>'syllabus'),null,true);
	  $x_previous_year=$this->url(array('controller'=>'icse', 'action'=>'previous-years'),null,true);
	  
	  $xii_sample_papers=$this->url(array('controller'=>'isc', 'action'=>'sample-papers'),null,true);
	  $xii_syllabus=$this->url(array('controller'=>'isc', 'action'=>'syllabus'),null,true);
	  $xii_previous_year=$this->url(array('controller'=>'isc', 'action'=>'previous-years'),null,true);
	  $practical=$this->url(array('controller'=>'isc', 'action'=>'isc-computer-practical'),null,true);
	  $viva=$this->url(array('controller'=>'isc', 'action'=>'viva-voce'),null,true);
	  $comp_project=$this->url(array('controller'=>'isc', 'action'=>'computer-project'),null,true);
	  
	  $javaQuiz=$this->url(array('controller'=>'fun','action'=>'java-quiz'),null,true);
	  $quiz=$this->url(array('controller'=>'fun'),null,true);
	  $brainteasers=$this->url(array('controller'=>'fun','action'=>'brainteasers'),null,true);
	  $doodle=$this->url(array('controller'=>'doodle'),null,true);
	  
	  $forum=$this->url(array('controller'=>'forum'),null,true);
	  $videos=$this->url(array('controller'=>'videos'),null,true);
	  //$gallery=$this->url(array('controller'=>'gallery'),null,true);
	  $gallery = "http://www.wethementors.com/gallery/index";
?>
<ul>
  <li>Home
    <ul>
		<li><a href="<?php echo $contact; ?>">Contact us</a></li>
		<li><a href="<?php echo $sitemap; ?>">Sitemap</a></li>
	</ul>
  </li>
  <li>Resources
	<ul>
	<li><a href="<?php echo $tutorials; ?>">Tutorials</a></li>
	<li><a href="<?php echo $poi; ?>">Persons of Eminence</a></li>
	<li><a href="<?php echo $ant; ?>">Installing Ant on Windows</a></li>
	</ul>
  </li>
  <li>Class X
	<ul>
	<li><a href='<?php echo $x_sample_papers; ?>'>Sample Papers</a></li>
	<li><a href='<?php echo $x_syllabus; ?>'>Syllabus</a></li>
	<li><a href='<?php echo $x_previous_year; ?>'>Previous Years</a></li>
	</ul>
  </li>
  <li>Class XII
  	<ul>
	<li><a href='<?php echo $xii_sample_papers; ?>'>Sample Papers</a></li>
	<li><a href='<?php echo $xii_syllabus; ?>'>Syllabus</a></li>
	<li><a href='<?php echo $xii_previous_year; ?>'>Previous Years</a></li>
	<li><a href='<?php echo $practical; ?>'>ISC Computer Practical</a></li>
	<li><a href='<?php echo $viva; ?>'>Viva</a></li>
	<li><a href='<?php echo $comp_project ?>'>Computer Project</a></li>
	</ul>
  </li>
  <li><a href="<?php echo $videos; ?>">Videos</a></li>
  <li><a href="<?php echo $gallery; ?>">Gallery</a></li>
  <li><a href="<?php echo $forum; ?>">Forum</a></li>
  <li>Fun
	<ul>
	  <li><a href='<?php echo $javaQuiz; ?>'>Java Quiz</a></li>
	  <li><a href='<?php echo $quiz; ?>'>Quiz</a></li>
	  <li><a href='<?php echo $brainteasers; ?>'>Brainteasers</a></li>
	  <li><a href='<?php echo $doodle; ?>'>Doodle</a></li>
	</ul>
  </li>
</ul>
<br style="clear:left" />
	  </div>
	</div>
<div id="contentWrapper">
	<div id="main">
	  <?php echo $this->layout()->content; ?>&nbsp;
	</div>
	<div id="sidebar_right">
<?php $mdlNotes=new Model_Notes();
	  $person=$mdlNotes->randomPerson('people');
	  $people=$this->url(array('controller'=>'resources', 'action'=>'people', 'pid'=>$person['id'], 'poi'=>$person['heading']),null, true);
	  $java=$this->url(array('controller'=>'fun','action'=>'java-quiz'),null,true);
	  ?>
	  
<fieldset class="home_right">
	  <legend>Do you know?</legend>
		<div class="divsContent">
	  <?php	  $mdlFunFacts=new Model_FunFacts(); $result=$mdlFunFacts->randomFact();  ?>
	  <p><?php echo $result->fact;?></p>
			<?php $funFacts=$this->url(array('controller'=>'fun', 'action'=>'fun-facts'),null, true); ?>
	  <a href="<?php echo $funFacts;?>">View more</a>
	  </div>
</fieldset>
<?php include_once APPLICATION_PATH.'/Misc/Util.php';?>
<?php
	$askQuestion=$this->url(array('controller'=>'programs','action'=>'ask-question'),null,true);
	$allQuestions=$this->url(array('controller'=>'programs','action'=>'questions'),null,true);	
?>
<br />	<div class="link_ques">
		<a href="<?php echo $askQuestion;?>">Ask a Question</a>
	</div><br />
	<div class="link_ques">
		<a href="<?php echo $allQuestions;?>">View All Questions</a>
	</div>
<br />
<fieldset class="home_right">
	  <legend>Quote Of The Day</legend>
		<div class="divsContent">
			<?php $mdlQuote=new Model_Quotes();
				  $quote=$mdlQuote->randomQuote();
			if($quote!=false){
				$escapedQuote=Util::convert_smart_quotes($quote->quote);
			?>
			<p><?php echo $escapedQuote;?> - <i><?php echo $quote->quote_by;?></i></p>
			<?php }?>
			<?php $allQuotes=$this->url(array('controller'=>'quotes', 'action'=>''),null, true); ?>
			<a href='<?php echo $allQuotes;?>'>View all quotes</a>
		</div>
</fieldset>
<fieldset class="home_right" style="border:none;">
<div class="g-plus" data-width="275" data-href="//plus.google.com/112434687978129571118?rel=publisher"></div>
</fieldset>
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
<div id="divsFb">
<!-- <div class="fb-like-box" data-href="http://www.facebook.com/pages/Mentors/179112368809235" data-width="290" data-show-faces="true" data-stream="false" data-header="true"></div> -->
    <div class="fb-like-box" data-href="http://www.facebook.com/wethementors" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
</div>
<div id="ad">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-1662490668144398";
/* Sidebar */
google_ad_slot = "2811909247";
google_ad_width = 250;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>

	</div>
</div>
</div>
<div id="Two4ka1">
	  <div id="copyright">
	  <span><?php
	  $pp=$this->url(array('controller'=>'home', 'action'=>'privacy-policy'),null,true);
	  $tou=$this->url(array('controller'=>'home', 'action'=>'terms-of-use'),null,true);?>
	  &copy;<?php echo strftime("%Y", time()); ?> Mentors. All Rights Reserved.
	  <a href="<?php echo $pp;?>">Privacy Policy</a> and <a href="<?php echo $tou;?>">Terms of Use</a>
	  </span><br />
	  <span><script type="text/javascript">document.write(Date());</script>
	  </span>
	  </div>

</div>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
window.___gcfg = {
lang: 'en-GB',
parsetags: 'onload'
};
</script>
</body>
</html>