<?php $this->headTitle()->set('English Language - Summary Writing, Precis');
echo $this->headTitle();
?>
<div class="content english">
	<div>
		<h1>English Language</h1>
            <h2> Summary Writing</h2>
            <blockquote>
                Write a short summary of each source as soon as you finish reading it to capture the gist of the
                author's argument or study.
                These summaries may be the most valuable notes you make.
                WHY?
            </blockquote>
            <ul>
                <li>Synthesis: Summaries help you pull together the general conclusions and
                    approaches of the experts, which you will refer to in your paper.
                </li>
                <li>
                    Focus & selection: As you focus your research, you can review the summaries to
                    see which references you should return to and study more carefully.
                </li>
                <li>
                    Speed: If you need more specific information from one of your sources, your
                    summaries will help you locate that source quickly.
                </li>
                <li>
                    Mastery of material: Summary writing is an active, not passive, process. You must
                    digest a reading and get it into your head in a coherent way to summarize it. This
                    helps you master the material for your paper.
                </li>
                <li>
                    Perspective: Reviewing the summaries will help you see the different points of view on a topic.
                </li>
             </ul>

            <h3>HOW?</h3>
            <ol>
                <li>  Put the source away, and then ask yourself these questions and answer them in your summary:
                    <ul>
                         <li>What problem was the author trying to understand/resolve?</li>
                    <li>What was his/her hypothesis?</li>
                    <li>What were the results?</li>
                    <li>What was the author's method or approach in developing his/her argument or testing
                    his/her thesis?</li>
                    <li>What perspective in the field is the author coming from?</li>
                    <li>What here could be useful for my research project?</li>
                    </ul>
                </li>
                <li> Use mainly your own words, perhaps with some short quoted excerpts. Check for accuracy.</li>
                <li> Be sure to include information on the source. You might write the summaries on the backs of your working bibliography cards.</li>
            </ol>
            <p>Source: <a href="http://www.cgu.edu/PDFFiles/Writing%20Center/Writing%20Center%20Resources/Writing%20Summary%20Notes.pdf">www.cgu.edu</a></p>
            <hr />

            <div class="google-ad">
                <?php require_once APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
            </div>

            <h2>Precis Writing</h2>
            <h3>ALL ABOUT PR&EacuteCIS WRITING</h3>
            <blockquote>
                A <i>pr&eacutecis</i> is a shortening, in your own words, of a text of written work. You are to describe as
                accurately and briefly as possible the substance or main ideas contained in a text.
                One of the first (if not the first) difficulties to overcome in writing a pr&eacutecis is getting
                the facts straight. You should make no statements unsupported by the text. Make sure that all you
                say about the text is factually correct.
            </blockquote>
            <p>
            Another difficulty is putting the material into your own words. To do so, read the work carefully
            at least three times, put the work aside, then begin writing. This will force you to use your own
            words without the temptation of borrowing directly from the original.</p><br />
            <p>
            Selecting the most effective details is also a difficulty. Work to pick out those details that are
            of greatest significance. Some details are more important than others, and you must chose details
            according to the scale of importance.</p><br />
            <p>
            Do not make any conclusions about the original, its audience, or anything relating to the text.
            Your job is to provide your reader an accurate, but brief, map of the original and what you think
            about the writing or the topic of the text is not relevant here.</p><br />
            <p>
            The <i>pr&eacutecis</i> (pronounced pray-see) is a type of summarizing that insists on an exact
            reproduction of the logic, organization, and emphasis of the original texts. It is of particular
            use in situations in which you want to detail the relative order, proportions, and relationships
            of the original parts of a text. An effective <i>pr&eacutecis</i> retains the logic, development, and
            argument of the original in much shorter form. Thus, a <i>pr&eacutecis</i> is useful when you are dealing
            with lengthy passages that demand careful attention to the logic and organization of an argument.
            </p>
                <div class="google-ad">
                    <?php require_once APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
                </div>
            <h3>
            To write an effective pr&eacutecis:</h3>
            <ul>
                 <li>Read the passage several times for a full understanding.</li>
                 <li>Note key points. It may, in fact, be helpful to underline these words.</li>
                 <li>Restate each paragraph in one or two sentences.</li>
                 <li>In cases where there are very short paragraphs, combine them in your restatement.</li>
                 <li>Make sure that you retain the precise order of the original points, and combine the sentences into one
            or more smooth paragraphs.</li>
                 <li>Finally, check your <i>pr&eacutecis</i> against the original to be sure that it is
            exact and retains the order, proportions, and relationships of the original.</li>
            </ul>
            <br />
            <h3>What is the essence of a pr&eacutecis?</h3>
            <p>

            It is a short summary of the essential ideas of a longer composition; the basic thought of a
            passage is reproduced in miniature, retaining the mood and tone of the original. No interpretation
            or comment should be interjected.</p><p> It must possess clear, emphatic diction and effective sentence construction.
            Its unity and coherence should be emphasized through smooth, unobtrusive transitions. Your summary must be
            intelligible to a reader who has not seen the original and should have solid compositional worth.</p>
            <p><i>
            100 - 200 words is the desired length of a <i>pr&eacutecis</i>, unless otherwise specified.  </i></p>
            <h3>How to write a pr&eacutecis?</h3>
            <p>
            First, write an outline of the main ideas - those you see as most important. Think of it this way -
            you are summarizing the lecture for a friend who missed the class and the material will be on an upcoming test.
            Also, you may want to include a brief statement about the tone, audience, or purpose of the article.</p>
            <p>
            Second, put your outline into sentence/paragraph form.
            Third, count the number of words and make necessary changes.</p>
            <br />
            <h3>Do's and Don'ts of Pr&eacutecis Writing</h3>

            <ul>
                 <li>
                Start your <i>pr&eacutecis</i> by creating context (setting) and stating the main idea of the piece.
                Then you should begin presenting the method that the author used to defend this thesis.</li>

            <li> Always state the name of the article/document, the author and the source (is it from a magazine,
                book, encyclopedia, etc.)</li>
            <li>
                Do not use the words "in this article." Use the style "Crane argues that the most significant
                contribution of the Czechs was . . "</li>
            <li>
                When writing about history, use the past tense.</li>
            <li>
                Do not use abbreviations or contractions.</li>
            <li>
                When looking at primary sources, you should make note of the origin, purpose, value, and limitations
                of the document. (See website on Evaluation of sources)</li>
            <li>
                Count your "ands."</li>
            <li>
                Avoid words like big, good, bad, little, and a lot. Also, do not use the phrase "throughout history."
                This is clich&eacute.</li>
            <li>
                Titles of texts should be put in italics OR underlined.</li>
            </ul>
            <p>
                <b>RUN A SPELL CHECK!!!</b>
            </p>

            <p>    Before writing all these first count the total number of all the words in that paragraph and divide it by 3
                example:</p>
            <p>150 words
                150/3=50
                so we have to finish the precis within 50 words</p>

	</div>
</div>