<style type="text/css">
    #auth{
        border: 1px solid #DDD;
        border-radius:1ex;
        margin: 20px;
        padding: 10px;
    }
    #auth h1 {
        color: #D2322D;
    }
    #auth p {
        font-size: 1.3em;
        padding: 5px;
        text-align: center;
    }
    #auth h3{
        color: #222;
        text-align: center;
    }
    #auth ul {
        display: block;
        margin: 20px auto;
        text-align: left;
        width: 80%;
    }
    #auth li {
        font-size: 1.3em;
        line-height: 1.5em;
        list-style-type: initial;
    }
</style>

<div class="content">
    <div class="content bg-warning text-center" id="auth">
        <h1>Whoops! Page not found.</h1>
        <h3>This may be due to one of following two reasons:</h3>
        <ul>
          <li>The page you are looking for might be in the process of updation. Kindly bear with us for a short time.</li>
          <li>You have mistyped a link. Follow the in-site links to navigate within the site.</li>
        </ul>
    </div>
</div>