<style type="text/css">
    #auth{
        border: 1px solid #DDD;
        border-radius:1ex;
        margin: 20px;
        padding: 10px;
    }
    #auth h1 {
        color: #D2322D;
    }
    #auth p {
        font-size: 1.3em;
        padding: 5px;
        text-align: center;
    }

</style>
<div class="content bg-warning" id="auth">
<h1>Error: Not Authorised!</h1>
<p> You are not authorised to access this resource.</p>
<?php $login=$this->url(array('controller'=>'user','action'=>'login'),null,true);?>
<p>Kindly <a href="<?php echo $login;?>">login</a> to avail the privilege.</p>
</div>