<?php //header('Page not found', true, 404);?>

<div class="content">
    <div class="content bg-warning " id="auth">
        <h1 class="text-danger">Whoops! Page not found.</h1><br />
        <h3>This may be due to one of the following two reasons:</h3>
        <ul class="text-muted">
          <li>The page you are looking for might be in the process of update. Kindly bear with us for a short time.</li>
          <li>You have mistyped a link. Follow the in-site links to navigate within the site.</li>
        </ul>
    </div>
</div>
<style type="text/css">
	#auth {
		border: 1px solid #ddd;
		border-radius: 1ex;
		margin: 50px auto;
		max-width: 768px;
		padding: 20px 50px;
	}
	#auth h1 {
		text-align: center;
	}
	#auth p {
		font-size: 1.3em;
		padding: 5px;
	}
	#auth ul {
		margin: 20px 0 20px 40px;
	}
	#auth li {
		font-size: 18px;
	}
</style>
