<?php require_once APPLICATION_PATH.'/Misc/Util.php'; ?>
<?php
    $this->headTitle()->set("Question/Answers");
    echo $this->headTitle();
    $askQuestion = $this->url(array('controller'=>'qa','action'=>'ask-question'),null,true);
    $allQuestions = $this->url(array('controller'=>'qa','action'=>'questions'),null,true);
    $recent = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => 'recent'),null,true);
    $popular = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => 'popular'),null,true);
    $unanswered = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => 'unanswered'),null,true);
    if($this->sorter != 'recent')
        $qaLink = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => $this->sorter, 'page' => ''),null,true);
    else
        $qaLink = $this->url(array('controller'=>'qa','action'=>'index', 'page' => ''),null,true);
?>
<div id="main" class="question_area col-sm-12 col-md-8 col-lg-9">
    <div class="q_head clearfix">
        <div class="q_head_static col-xs-12 text-left col-md-6">
            <h1 class="text-center"><?php echo ucwords($this->sorter); ?> Questions</h1>
        </div>
        <div class="q_head_links col-xs-12 col-md-6 text-right">
            <a href="<?php echo $recent; ?>" class="btn btn-sm btn-primary <?php echo $this->sorter == 'recent'? 'disabled': ''; ?>">Recent</a>
            <a href="<?php echo $popular; ?>" class="btn btn-sm btn-danger <?php echo $this->sorter == 'popular'? 'disabled': ''; ?>">Popular</a>
            <a href="<?php echo $unanswered; ?>" class="btn btn-sm btn-warning <?php echo $this->sorter == 'unanswered'? 'disabled': ''; ?>">Unanswered</a>
        </div>
        <div class="clearfix"></div>
        <hr />
    </div>
    <?php if(isset($this->paginator)){ ?>
    <!--    <div class="q_ech clearfix">-->
<!--      <div class="clearfix">-->
<!--        <div class="response_q col-md-10 col-md-offset-2">-->
<!--            --><?php //require_once APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
    <?php $c=0; foreach($this->paginator as $question){$c++;?>
        <?php
            $created = strtotime($question['created']);
            $t = Util::makeTime($created);
            $quesLink = $this->url(array('controller'=>'qa','action'=>'questions','id'=>$question['id']),null,true);
            $dpThumb = $question['dp'];

            if($dpThumb == null){
                if($question['gender']=='m')
                    $dpThumb = "/images/placeholder_male.png";
                else
                    $dpThumb = "/images/placeholder_female.png";
            }
            $userLink = $this->url(array('controller'=>'profile', 'action'=>'index','user'=>$question['username']),null,true);
            $tagLink = $this->url(array('controller' => 'QA', 'action' => 'questions'),null,true);
            $description = strlen($question['description']) >= 200? substr($question['description'],0,200)."...":$question['description'];
            $noa = isset($question['answer_count']) && !empty($question['answer_count'])?$question['answer_count']:0;
            $nov = isset($question['vote_count']) && !empty($question['vote_count'])?$question['vote_count']:0;
        ?>
        <div class="q_ech clearfix">
          <div class="clearfix">
            <div class="response_q col-xs-3 col-sm-3 col-md-2">
                <div class="metrics text-center">
                    <div class="vote-counts">
                        <span><?php echo $nov ;?></span>
                        <div class="vote-count">votes</div>
                    </div>
                    <div class="ans-counts">
                        <span><?php echo $noa ;?></span>
                        <div class="ans-count">answers</div>
                    </div>
                </div>
            </div>
            <div class="reply_q col-xs-9 col-sm-9 col-md-10">
                <?php if($this->uid==$question['uid']):?>
                    <span class="post_rc pull-right hide" onclick="rtc(this);"><img src="<?php echo $this->baseUrl();?>/images/del.png" title="Delete this question" alt="Delete this question" /></span>
                <?php endif; ?>
                <h3 class="btn-block"><a href="<?php echo $quesLink;?>"><?php echo htmlentities($question['question']);?></a></h3>
                <input type="hidden" value="<?php echo $question['id'];?>" />

                <div class="feedback col-md-12">
                    <?php echo $description; ?>
                </div>
                <br />
                <div class="tags col-xs-6 col-md-8">
                    <?php
                    $tags = $question['tags'];
                    if(!empty($tags)): ?>
                    <?php foreach(explode(",",$tags) as $tag): ?>
                            <a href="<?php echo $tagLink."/tagged/".$tag;?>" title="<?php echo $tag; ?>"><?php echo $tag; ?></a>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <div class="asker col-xs-6 col-md-4 clearfix">
                    <div class="asker_pic pull-left">
                        <a href="<?php echo $userLink;?>"><img src="<?php echo BASE_URL.$dpThumb; ?>" alt="<?php echo $question['username'];?>" title="<?php echo $question['username'];?>" /></a>
                    </div>
                    <div class="asker_username pull-left">
                        <a class="username" href="<?php echo $userLink;?>"><?php echo $question['username'];?></a>
                        <span class="date_asked">asked <?php echo $t;?></span>
                    </div>
                </div>
            </div>
          </div>
         <hr />
        </div>
        <?php }	?>
    <br />

    <div id="pagination" class="pagination">
        <div class="controls text-center">
            <?php
                echo $this->paginationControl($this->paginator,
                'Sliding',
                'includes/paginationcontrolQ.phtml',
                array('link' => $qaLink)
                );
            ?>
        </div>
    </div>

    <?php  }elseif(isset($this->msg)){?>
        <h2 style="margin:30px 10px; text-align:center;">No question has been asked so far. If you have a problem, ask your question <a href="<?php echo $askQuestion; ?>">here</a>.</h2>
    <?php } ?>
</div>

<div id="sidebar_right" class="col-sm-12 col-md-4 col-lg-3">
    <fieldset class="home_right text-center google-ad">
<!--        --><?php //include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
    </fieldset>
    <fieldset class="home_right">
        <a class="btn btn-success" href="<?php echo $askQuestion;?>">Ask Question</a>
        <a class="btn btn-success" href="<?php echo $allQuestions;?>">View All Questions</a>
    </fieldset>
    <fieldset class="home_right text-center" id="tags">
        <?php include APPLICATION_PATH.'/../layouts/templates/quesByTopic.php'; ?>
    </fieldset>
</div>