<?php require_once APPLICATION_PATH.'/Misc/Util.php'; ?>
<?php
    $askQuestion=$this->url(array('controller'=>'qa','action'=>'ask-question'),null,true);
    $allQuestions=$this->url(array('controller'=>'qa','action'=>''),null,true);
    $recent = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => 'recent'),null,true);
    $popular = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => 'popular'),null,true);
    $unanswered = $this->url(array('controller'=>'qa','action'=>'index', 'sort' => 'unanswered'),null,true);
//    $login=$this->url(array('controller'=>'user','action'=>'login'),null,true).'?next='. urlencode('http://localhost/wethementors/public/QA/questions/id/'.$this->question['id']);
    $tagLink = $this->url(array('controller'=>'QA', 'action'=>'questions'),null,true);
   if(isset($this->tag))
        $qaLink = $this->url(array('controller'=>'qa','action'=>'questions', 'tagged' => $this->tag, 'page' => ''),null,true);

?>

<div id="main" class="qa-cont col-sm-12 col-md-8 col-lg-9" xmlns="http://www.w3.org/1999/html">
    <?php if(isset($this->paginator)): ?>
        <?php
            $this->headTitle()->set("Questions tagged: \"".$this->tag."\"");
            echo $this->headTitle();
        ?>
    <div class="tagged_container">
        <div class="q_head clearfix">
            <div class="q_head_static col-xs-6 col-md-6 col-xs-offset-1 col-md-offset-1">
                <h1 class="text-center">Questions tagged: "<?php echo $this->tag; ?>"</h1>
            </div>
            <div class="q_head_links col-xs-5 col-md-5 text-right">
                <a href="<?php echo $recent; ?>" class="btn btn-primary <?php echo $this->sorter == 'recent'? 'disabled': ''; ?>">Recent</a>
                <a href="<?php echo $popular; ?>" class="btn btn-danger <?php echo $this->sorter == 'popular'? 'disabled': ''; ?>">Popular</a>
                <a href="<?php echo $unanswered; ?>" class="btn btn-warning <?php echo $this->sorter == 'unanswered'? 'disabled': ''; ?>">Unanswered</a>
            </div>
        </div>

        <hr />

            <?php $c=0; foreach($this->paginator as $question){$c++;?>
                <?php
                $created=strtotime($question['created']);
                $current=strtotime(date('Y-m-d H:i:s', time()+5.5*60*60));
                $t=Util::makeTime($created);
                $quesLink=$this->url(array('controller'=>'qa','action'=>'questions','id'=>$question['id']),null,true);
                $dpThumb = $question['dp'];

                if($dpThumb == null){
                    if($question['gender']=='m')
                        $dpThumb="/images/placeholder_male.png";
                    else
                        $dpThumb="/images/placeholder_female.png";
                }
                $userLink = $this->url(array('controller'=>'profile', 'action'=>'index','user'=>$question['username']),null,true);
                $description = strlen($question['description']) >= 200? substr($question['description'],0,200)."...":$question['description'];
                $noa = isset($question['answer_count']) && !empty($question['answer_count'])?$question['answer_count']:0;
                $nov = isset($question['vote_count']) && !empty($question['vote_count'])?$question['vote_count']:0;
            ?>
            <div class="q_ech clearfix">
                <div class="clearfix">
                    <div class="response_q col-xs-3 col-sm-3 col-md-2">
                        <div class="metrics text-center">
                            <div class="vote-counts">
                                <span><?php echo $nov ;?></span>
                                <div class="vote-count">votes</div>
                            </div>
                            <div class="ans-counts">
                                <span><?php echo $noa ;?></span>
                                <div class="ans-count">answers</div>
                            </div>
                        </div>
                    </div>
                    <div class="reply_q col-xs-9 col-sm-9 col-md-10">
                        <?php if($this->uid==$question['uid']):?>
                        <span class="post_rc pull-right hide" onclick="rtq(this);"><img src="<?php echo $this->baseUrl();?>/images/del.png" title="Delete this question" alt="Delete this question" /></span>
                        <?php endif; ?>
                        <h3 class="btn-block"><a href="<?php echo $quesLink;?>"><?php echo htmlentities($question['question']);?></a></h3>
                        <input type="hidden" value="<?php echo $question['id'];?>" />

                        <div class="feedback col-md-12">
                            <?php echo $description; ?>
                        </div>
                        <br />
                        <div class="tags col-xs-6 col-md-8">
                            <?php
                            $tags = $question['tags'];
                            if(!empty($tags)): ?>
                                <?php foreach(explode(",",$tags) as $tag): ?>
                                    <a class="tag" href="<?php echo $tagLink."/tagged/".$tag; ?>" title="<?php echo $tag; ?>"><?php echo $tag; ?></a>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                        </div>
                        <div class="asker col-xs-6 col-md-4 clearfix">
                            <div class="asker_pic pull-left">
                                <a href="<?php echo $userLink;?>"><img src="<?php echo BASE_URL.$dpThumb; ?>" alt="<?php echo $question['username'];?>" title="<?php echo $question['username'];?>" /></a>
                            </div>
                            <div class="asker_username pull-left">
                                <a class="username" href="<?php echo $userLink;?>"><?php echo $question['username'];?></a>
                                <span class="date_asked">asked <?php echo $t;?></span>
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
            </div>
                <?php }	?>
        <br />
        <div id="pagination" class="pagination">
            <div class="controls text-center">
                <?php
                echo $this->paginationControl($this->paginator,
                'Sliding',
                'includes/paginationcontrolQ.phtml',
                array('link' => $qaLink)
                );
                ?>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="qa-single">
        <?php if(isset($this->question) && !empty($this->question)):?>
        <?php
            $this->headTitle()->set(substr($this->question['question'],0,50).(strlen($this->question['question'])>=50?"...":""));
            echo $this->headTitle();
            $question = $this->question;
            $loginUrl = $this->url(array('controller'=>'user','action'=>'login'),null,true).'?next='. urlencode(BASE_URL.'QA/questions/id/'.$this->question['id']);
            $dpThumb = $question['dp'];
            if($dpThumb == null){

                if($question['gender']=='m')
                    $dpThumb="/images/placeholder_male.png";
                else
                    $dpThumb="/images/placeholder_female.png";
            }

            $userLink=$this->url(array('controller'=>'profile', 'action'=>'index','user'=>$question['username']),null,true);
            if(isset($this->username))
                $curUserLink=$this->url(array('controller'=>'profile', 'action'=>'index','user'=>$this->username),null,true);
            else
                $curUserLink="#";
            $votes = intval($question['upvotes'])-intval(($question['downvotes']));
            $own = $this->uid == $question['uid']?' own':'';
            $login = $this->uid == -1?' login':'';
            $userVotes = $this->userQuestionVotes;
            if(is_array($this->userQuestionVotes) && array_key_exists($question['id'], $this->userQuestionVotes)){
                $upvoted = intval($userVotes[$question['id']]) == 1? ' vu': '';
                $downvoted = intval($userVotes[$question['id']]) == -1? ' vd': '';
            }else{
                $upvoted = $downvoted = '';
            }
        ?>
        <div class="aqc clearfix">
            <h1 class="col-md-offset-2"><a href=""><?php echo $this->question['question'];?></a></h1><br />
            <div class="aqc-vc col-xs-2 col-sm-2 col-md-2">
                <div class="metrics text-center pull-right">
                    <div class="alert alert-dismissable alert-warning vote-error hide" role="alert">
                        <button type="button" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <p>You cannot vote on your own question.</p>
                    </div>
                    <div onclick="qv(this,1)" class="arrow-up vote-i <?php echo $own.$login.$upvoted; ?>" title="This question is useful"></div>
                    <div class="qv-count">
                        <p><?php echo $votes; ?></p>
                    </div>
                    <div onclick="qv(this,-1)" class="arrow-down vote-i <?php echo $own.$login.$downvoted; ?>" title="This answer is not useful"></div>
                </div>
            </div>
            <div class="aqc-qc col-xs-10 col-sm-10 col-md-10">
                <input type="hidden" value="<?php echo $question['id'];?>" />
                <?php
                    $created=strtotime($question['created']);
                    $t=Util::makeTime($created);
                ?>
                <div class="feedback col-md-11">
                    <?php echo nl2br($question['description']); ?>
                </div>
                <div class="user-action col-xs-1 col-sm-1 col-md-1 col-lg-1">
                    <?php if($this->uid == $question['uid']):?>
                        <span class="post_rc pull-right hide" onclick="rtq(this);"><img src="<?php echo $this->baseUrl();?>/images/del.png" title="Delete this question" alt="Delete this question" /></span>
                    <?php endif; ?>
                </div>
                <br />
                <div class="tags col-xs-6 col-md-8">
                    <?php
                    $tags = $question['tags'];
                    if(!empty($tags)): ?>
                        <?php foreach(explode(",",$tags) as $tag): ?>
                            <a href="<?php echo $tagLink."/tagged/".$tag;?>" title="<?php echo $tag; ?>"><?php echo $tag; ?></a>
                            <?php endforeach; ?>
                        <?php endif; ?>
                </div>
                <div class="asker col-xs-6 col-md-4 clearfix">
                    <div class="asker_pic pull-left">
                        <a href="<?php echo $userLink;?>"><img src="<?php echo BASE_URL.$dpThumb; ?>" alt="<?php echo $question['username'];?>" title="<?php echo $question['username'];?>" /></a>
                    </div>
                    <div class="asker_username pull-left">
                        <a class="username" href="<?php echo $userLink;?>"><?php echo $question['username'];?></a>
                        <span class="date_asked">asked <?php echo $t;?></span>
                    </div>
                </div>
            </div>
        </div>
        <div id="user_sols">
            <?php if(!empty($this->answers)): ?>
                <p class="noc col-md-offset-1"><?php echo count($this->answers); ?> answers</p>
                <?php $ctr = 1; ?>
                <?php foreach($this->answers as $answer):?>
                    <?php $votes = intval($answer['upvotes'])-intval(($answer['downvotes']));
                          $own = $this->uid == $answer['uid']?' own':'';
                          $login = $this->uid == -1?' login':'';
                        $userVotes = $this->userAnswerVotes;
                        if(is_array($this->userAnswerVotes) && array_key_exists($answer['id'], $this->userAnswerVotes)){
                            $upvoted = intval($userVotes[$answer['id']]) == 1? ' vu': '';
                            $downvoted = intval($userVotes[$answer['id']]) == -1? ' vd': '';
                        }else{
                            $upvoted = $downvoted = '';
                        }
                    ?>
                    <div class="aoq">
                        <div class="clearfix">
                            <div class="aqc-vc col-xs-2 col-sm-2 col-md-2">
                                <div class="metrics text-center pull-right">
                                    <div class="alert alert-dismissable alert-warning vote-error hide" role="alert">
                                        <button type="button" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        <p>You cannot vote on your own answer.</p>
                                    </div>
                                    <div onclick="acv(this,1)" class="arrow-up vote-i <?php echo $own.$login.$upvoted; ?>" title="This answer is useful"></div>
                                        <div class="qv-count">
                                            <p><?php echo $votes; ?></p>
                                        </div>
                                    <div onclick="acv(this,-1)" class="arrow-down vote-i <?php echo $own.$login.$downvoted; ?>" title="This answer is not useful"></div>
                                </div>
                            </div>
                            <div class="aqc-qc res_cont col-xs-10 col-sm-10 col-md-10">
                                <input type="hidden" value="<?php echo $answer['id'];?>" />
                                <?php
                                    $dpThumb = $answer['dp'];
                                    if($dpThumb==""){
                                        if($answer['gender']=='m')
                                            $dpThumb="/images/mt.png";
                                        else
                                            $dpThumb="/images/ft.png";
                                    }else{
                                        $dpThumb="/users/thumbs/".$answer['username'];
                                    }
                                    $userLink=$this->url(array('controller'=>'profile', 'action'=>'index','user'=>$answer['username']),null,true);
                                    $created=strtotime($answer['created']);
                                    $t=Util::makeTime($created);
                                ?>
                                <div class="feedback col-md-12">
                                    <?php if($this->uid==$answer['uid']):?>
                                        <span class="post_rc pull-right hide" onclick="rta(this);"><img src="<?php echo $this->baseUrl();?>/images/del.png" title="Delete answer" alt="Delete answer" /></span>
                                    <?php endif; ?>
                                    <p class="reply_text"><?php echo nl2br(($answer['answer']));?></p>
                                </div>
                                <br />
                                <div class="asker col-xs-6 col-md-4 col-md-offset-8 clearfix">
                                    <div class="asker_pic pull-left">
                                        <a href="<?php echo $userLink;?>">
                                            <img src="<?php echo BASE_URL.$dpThumb;?>" alt="<?php echo $answer['username'];?>" title="<?php echo $answer['username'];?>" />
                                        </a>
                                    </div>
                                    <div class="asker_username pull-left">
                                        <a class="username" href="<?php echo $userLink;?>"><?php echo $answer['username'];?></a>
                                        <span class="date_asked">answered <?php echo $t;?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <hr />
                    </div>
                    <?php if($ctr == 1): ?>
                        <div class="aoq">
                            <div class="clearfix">
                                <div class="google-ad col-md-offset-2 col-md-10 text-center">
        <!--                        --><?php //include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
                                </div>
                            </div>
                            <hr />
                        </div>
                    <?php $ctr++; else:?>
                <?php endif;?>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="clearfix">
                    <div class="aqc-vc col-md-offset-2 col-md-10">
                        <p class="nosol">No solutions for this question so far. Share this question on Facebook, Google, Twitter or
                            <?php if($this->uid == $question['uid']):?>
                                answer your question.
                            <?php else: ?>
                                answer this question.
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="aqc res_c col-md-offset-2">
           <?php if($this->uid != -1): ?>
            <h3 class="text-left">Your Answer</h3>
            <div class="comment_post">
                <textarea name="answer"></textarea>
            </div>
            <div class="post-options">
                <button class="btn btn-primary" onclick="aans(this);">Post your answer</button>
                <div class="loading hide"><img src="<?php echo $this->baseUrl(); ?>/images/loading-s.gif" alt="loading..." /></div>
            </div>
            <?php else: ?>
                <p><a class="btn btn-primary" href="<?php echo $loginUrl; ?>">Log in </a>to your account to answer this questions.</p>
            <?php endif; ?>
        </div>
        <div class="other-options">
            <p>Not the answer you're looking for?
            <?php
                $tags = $question['tags'];
                if(!empty($tags)): ?>
                    Browse other questions tagged
                    <span class="tags">
                        <?php foreach(explode(",",$tags) as $tag): ?>
                            <a href="<?php echo $tagLink."/tagged/".$tag;?>" title="<?php echo $tag; ?>"><?php echo $tag; ?></a>
                        <?php endforeach; ?>
                    </span>
            <?php else: ?>
                    Browse <a href="<?php echo $allQuestions; ?>">other</a> questions.
            <?php endif; ?>
                or <a href="<?php echo $askQuestion; ?>">ask your own question.</a></p>
        </div>

            <?php else: ?>
            <div class="alert alert-danger text-center">
                <p>Question not found. This question may have been deleted by the asker.</p>
            </div>
                <div class="">
                    Browse <a href="<?php echo $allQuestions; ?>">other</a> questions.
                    or <a href="<?php echo $askQuestion; ?>">ask your own question.</a></p>
                </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
</div>

<div id="sidebar_right" class="col-sm-12 col-md-4 col-lg-3 qna">
    <fieldset class="home_right text-center">
        <a class="btn btn-success" href="<?php echo $askQuestion;?>">Ask Question</a>
        <a class="btn btn-success" href="<?php echo $allQuestions;?>">View All Questions</a>
    </fieldset>
    <?php if(!empty($this->relatedQuestions)): ?>
    <fieldset class="home_right related-ques">
        <legend>Related Questions</legend>
        <ul>
            <?php foreach($this->relatedQuestions as $question) :
                $quesLink = $this->url(array('controller'=>'qa','action'=>'questions','id'=>$question['id']),null,true);
            ?>
            <li  class="clearfix">
                <p title="Total votes on this question"><?php echo !empty($question['vote_count'])?$question['vote_count']:0; ?></p>
                <div class="link-cont">
                    <a href="<?php echo $quesLink; ?>"><?php echo substr($question['question'], 0, 100); echo strlen($question['question'])>=100?'...':''; ?></a>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </fieldset>
    <?php endif; ?>
    <fieldset class="home_right google-ad vert400">
<!--                --><?php //include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
    </fieldset>
    <fieldset class="home_right" id="tags">
        <?php include APPLICATION_PATH.'/../layouts/templates/quesByTopic.php'; ?>
    </fieldset>
</div>