<?php
	$this->headTitle()->set('ICSE Previous Years\' Papers');
	echo $this->headTitle();
?>
<div class="resources">
    <h1>ICSE Previous Years Papers</h1>
    <div class="paperList">
        <h3>Computer Applications</h3>
        <div class="papers">
            <ul>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/icse/ICSE_2005.doc'); ?>" title="ICSE Computer Applications 2005">ICSE 2005</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/icse/ICSE_2006.doc'); ?>" title="ICSE Computer Applications 2006">ICSE 2006</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/icse/ICSE_2007.doc'); ?>" title="ICSE Computer Applications 2007">ICSE 2007</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/icse/ICSE_2008.doc'); ?>" title="ICSE Computer Applications 2008">ICSE 2008</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/icse/ICSE_2009.doc'); ?>" title="ICSE Computer Applications 2009">ICSE 2009</a></li>
            </ul>
        </div>
    </div>
    <div class="google-ad">
        <?php include APPLICATION_PATH.'/../layouts/templates/ads/google-ad-horizontal.php'; ?>
    </div>
</div>