<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
	<div class="paginationControl text-center">
<!--		<div class="">-->
<!--		Showing --><?php //echo $this->firstItemNumber; ?><!-- - --><?php //echo $this->lastItemNumber; ?>
<!--		of -->
<!--			--><?php //echo $this->totalItemCount; ?>
<!--		</div>-->
<!--		<br />-->
		<!-- First page link -->
		<?php if (isset($this->previous)): ?>
			<a href="?page=<?php echo $this->first; ?>">
				First
			</a> |
		<?php else: ?>
			<span class="disabled">First</span> |
		<?php endif; ?>

		<!-- Previous page link -->
		<?php if (isset($this->previous)): ?>
			<a href="?page=<?php echo $this->previous; ?>">
				&laquo; Previous
			</a> |
		<?php else: ?>
			<span class="disabled">&laquo; Previous</span> |
		<?php endif; ?>

		<!-- Next page link -->
		<?php if (isset($this->next)): ?>
			<a href="?page=<?php echo $this->next; ?>">
				Next &raquo;
			</a> |
		<?php else: ?>
			<span class="disabled">Next &raquo;</span> |
		<?php endif; ?>

		<!-- Last page link -->
		<?php if (isset($this->next)): ?>
			<a href="?page=<?php echo $this->last; ?>">
				Last
			</a>
		<?php else: ?>
			<span class="disabled">Last</span>
		<?php endif; ?>

	</div>
<?php endif; ?>