<?php $this->headTitle()->set('ISC Previous Years\' Papers');
echo $this->headTitle();
?>
<div class="col-xs-12 col-md-10 col-md-offset-1">
    <h2>ISC Previous Years Papers</h2><hr />
    <div class="col-xs-12 col-md-6 clearfix">
        <h3>Computer Science</h3>
        <div class="papers link-green">
            <ul>
                <li><a class="afds" href="/docs/isc/ISC_2005.doc" title="ISC Computer Science 2005 (Theory)">ISC 2005</a></li>
                <li><a class="afds" href="/docs/isc/ISC_2006.doc" title="ISC Computer Science 2006 (Theory)">ISC 2006</a></li>
                <li><a class="afds" href="/docs/isc/ISC_2007.doc" title="ISC Computer Science 2007 (Theory)">ISC 2007</a></li>
                <li><a class="afds" href="/docs/isc/ISC_2008.doc" title="ISC Computer Science 2008 (Theory)">ISC 2008</a></li>
                <li><a class="afds" href="/docs/isc/ISC_2009.doc" title="ISC Computer Science 2009 (Theory)">ISC 2009</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad-rectangle.php'; ?>
    </div>

</div>