<?php $this->headTitle()->set('ISC Sample Papers');
echo $this->headTitle();
?>
<div class="col-xs-12 col-md-11 col-md-offset-1 link-green">
    <h1 class="text-center">ISC Sample Papers, ISC Guess Papers</h1><hr />
    <div class="col-xs-12 col-md-4">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad-vertical.php'; ?>
    </div>

    <div class="col-xs-12 col-md-4">
        <h3>Computer Science</h3>
        <div class="papers">
            <ul>
                <li><a class="afds" href="/docs/isc/Computer_Sample_Paper_1.doc" title="Computer Science Sample Paper - 1">Sample Paper - 1</a></li>
                <li><a class="afds" href="/docs/isc/Computer_Sample_Paper_2.doc" title="Computer Science Sample Paper - 2">Sample Paper - 2</a></li>
                <li><a class="afds" href="/docs/isc/Computer_Sample_Paper_3.doc" title="Computer Science Sample Paper - 3">Sample Paper - 3</a></li>
            </ul>
        </div>
        <h3>Mathematics</h3>
        <div class="papers">
            <ul>
                 <li><a class="afds" href="/docs/isc/Mathematics_Sample_Paper_1.doc" title="Mathematics Sample Paper - 1">Sample Paper - 1</a></li>
                 <li><a class="afds" href="/docs/isc/Mathematics_Sample_Paper_2.doc" title="Mathematics Sample Paper - 2">Sample Paper - 2</a></li>
                 <li><a class="afds" href="/docs/isc/Mathematics_Sample_Paper_3.doc" title="Mathematics Sample Paper - 3">Sample Paper - 3</a></li>
                 <li><a class="afds" href="/docs/isc/Mathematics_Sample_Paper_4.doc" title="Mathematics Sample Paper - 4">Sample Paper - 4</a></li>
             </ul>
        </div>
        <h3>Economics</h3>
        <div class="papers">
            <ul>
                 <li><a class="afds" href="/docs/isc/Economics_Sample_Paper_1.doc" title="Economics Sample Paper - 1">Sample Paper - 1</a></li>
                 <li><a class="afds" href="/docs/isc/Economics_Sample_Paper_2.doc" title="Economics Sample Paper - 2">Sample Paper - 2</a></li>
                 <li><a class="afds" href="/docs/isc/Economics_Sample_Paper_3.doc" title="Economics Sample Paper - 3">Sample Paper - 3</a></li>
            </ul>
        </div>
    </div>
    <div class="col-xs-12 col-md-4">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
    </div>
</div>