<?php $this->headTitle()->set('Riddles/Brainteasers');
echo $this->headTitle();
?>
<link  href="<?php echo $this->baseUrl();?>/skins/reds/css/quiz.css" media="screen" rel="stylesheet" type="text/css" >
<div class="content">
	<h1 class="text-center">Brainteasers/Riddles</h1><hr />
<?php if($this->paginator):?>
    <div id="riddles">
    <ol>
        <?php $c=0;	foreach($this->paginator as $riddle):$c++;?>
        <li><?php echo $riddle->riddle;?>
        <br /><button class="btn btn-primary">View/Hide Answer</button>
        <div class="solution quiz_answer hide">
            <p><?php echo (nl2br($riddle->answer));?></p>
        </div>
        </li><br />
        <?php if($c==6):?>
            <div class="google-ad">
                <?php require_once APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
            </div>
        <?php endif; ?>
        <?php if($c==18):?>
            <div class="google-ad">
                <?php require_once APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
            </div>
        <?php endif; ?>
        <?php endforeach;?>
    </ol>
    </div>
    <div id="pagination" class="pagination">
        <div class="controls">
            <?php   echo $this->paginationControl($this->paginator,
                        'Sliding',
                        'includes/paginationcontrol2.phtml');
            ?>
        </div>
    </div>
    <?php endif;?>
</div>