<?php $this->headTitle()->set('Fun Facts');
echo $this->headTitle();
?>
<div id="main" class="col-sm-7 col-lg-9">
    <div class="content">
        <h1 class="text-center">Fun Facts</h1>
        <?php if($this->paginator):?>
            <div class="facts-cont">
                <div class="clearfix">
                    <?php $ctr = 1;?>
                    <div class="col-sm-12 alpha">
                        <?php $funFact = $this->paginator;?>
                        <?php $c=1; foreach($funFact as $key => $record):?>
                            <div class="facts" id="fact-<?php echo $record->id; ?>">
                                <div class="fact">
                                    <?php echo $record->fact;?>
                                </div>
                                <div class="share-g">
                                    <div class="n_o_s"></div>
                                    <div class="center-block fb-fact-publish btn btn-primary">
                                        Share on Facebook
                                    </div>
                                </div>
                            </div>
                            <?php if($c%6 == 0): ?>
                                <div class="facts ad">
                                    <?php include APPLICATION_PATH.'/../layouts/templates/google-ad-rectangle.php'; ?>
                                </div>
                            <?php endif; ?>
                            <?php $c++; endforeach; ?>
                    </div>
                </div>
                <hr />
                <div id="pagination" class="pagination">
                    <div class="controls text-center">
                        <?php		echo $this->paginationControl($this->paginator,
                            'Sliding',
                            'includes/paginationcontrol2.phtml');
                        ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<div class="col-sm-5 col-lg-3" id="sidebar_right">
    <fieldset class="home_right text-center google-ad">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <?php require_once APPLICATION_PATH.'/../layouts/templates/qotd.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <?php require_once APPLICATION_PATH.'/../layouts/templates/gplus.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <?php require_once APPLICATION_PATH.'/../layouts/templates/fb.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <?php include_once APPLICATION_PATH.'/../layouts/templates/quick-links.php'; ?>
    </fieldset>
</div>
