<?php $this->headTitle()->set('Inventions Quiz');
echo $this->headTitle();
?>
<div class="content quiz">
<link  href="<?php echo $this->baseUrl();?>/skins/greens/css/quiz.css" media="screen" rel="stylesheet" type="text/css" >
<div id="quiz_container">
<h1>The Inventions Quiz</h1>
<p style="text-align:center">Choose the correct option for each of the
questions given below to score maximum points.</p>
<div class="quiz_info">
<p><b>Note:</b> <br /><b>*</b> Do not leave the quiz area before submitting your answers else the quiz will reset.</p>
<hr style="color:#eee;" /><br />
<script type="text/javascript"><!--
google_ad_client = "ca-pub-1662490668144398";
/* quiz */
google_ad_slot = "9839640907";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

<script type="text/javascript"><!--
google_ad_client = "ca-pub-1662490668144398";
/* quiz */
google_ad_slot = "9839640907";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
	<div id="quiz_form">
	<?php echo $this->form;?>
	</div>
	</div>
</div>