<?php $this->headTitle()->set('Trivia');
echo $this->headTitle();
?>
    <div class="content bg">
        <h1 class="text-center">Trivia</h1><hr />
        <?php if($this->paginator):?>
            <div class="facts-cont">
                <div class="clearfix">
                    <?php $ctr = 1;?>
                    <div class="col-sm-12 alpha">
                        <?php $trivia = $this->paginator;?>
                        <?php $c=1; foreach($trivia as $key => $record):?>
                            <div class="facts" id="fact-<?php echo $record->id; ?>">
                                <div class="fact">
                                    <?php echo $record->fact;?>
                                </div>
                                <div class="share-g">
                                    <div class="n_o_s"></div>
                                    <div class="center-block fb-fact-publish btn btn-primary">
                                        Share on Facebook
                                    </div>
                                </div>
                            </div>
                            <?php if($c%6 == 0): ?>
                                <div class="facts ad">
                                    <?php include APPLICATION_PATH.'/../layouts/templates/ads/google-ad-rectangle.php'; ?>
                                </div>
                            <?php endif; ?>
                            <?php $c++; endforeach; ?>
                    </div>
                </div>
                <hr />
                <div id="pagination" class="pagination">
                    <div class="controls text-center">
                        <?php		echo $this->paginationControl($this->paginator,
                            'Sliding',
                            'includes/paginationcontrol2.phtml');
                        ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
