<?php $this->headTitle()->set('ICSE - Syllabus, Sample Papers, Previous Years\' Papers');
echo $this->headTitle();
?>
<div class="content text-center link-green">
    <?php
          $syllabus=$this->url(array('controller'=>'icse', 'action'=>'syllabus'),null,true);
          $sample=$this->url(array('controller'=>'icse', 'action'=>'sample-papers'),null,true);
          $previous=$this->url(array('controller'=>'icse', 'action'=>'previous-years'),null,true);
    ?>

        <h2>ICSE</h2><hr />
        <ul>
            <li><a href="<?php echo $syllabus; ?>">Syllabus</a></li>
            <li><a href="<?php echo $sample; ?>">Sample Papers</a></li>
            <li><a href="<?php echo $previous; ?>">Previous Years' Papers</a></li>
        </ul>
</div>