<?php $this->headTitle()->set('ICSE Sample Papers');
echo $this->headTitle();
?>
<div class="col-xs-12 col-md-10 col-md-offset-1 link-green">
	<h2>ICSE Sample Papers, ICSE Guess Papers</h2><hr />
        <div class="col-xs-12 col-md-6">
                <h3>Physics</h3>
                <div class="papers">
                        <ul>
                            <li><a class="afds" href="<?php echo $this->baseUrl();?>/docs/icse/Physics_Sample_Paper_1.doc" title="Sample Paper Physics - 1">Sample Paper Physics - 1</a></li>
                            <li><a class="afds" href="/docs/icse/Physics_Sample_Paper_2.doc" title="Sample Paper Physics - 2">Sample Paper Physics - 2</a></li>
                            <li><a class="afds" href="/docs/icse/Physics_Sample_Paper_3.doc" title="Sample Paper Physics - 3">Sample Paper Physics - 3</a></li>
                            <li><a class="afds" href="/docs/icse/Physics_Sample_Paper_4.doc" title="Sample Paper Physics - 4">Sample Paper Physics - 4</a></li>
                            <li><a class="afds" href="/docs/icse/Physics_Sample_Paper_5.doc" title="Sample Paper Physics - 5">Sample Paper Physics - 5</a></li>
                        </ul>
                </div>
                <h3>Chemistry</h3>
                <div class="papers">
                        <ul>
                            <li><a class="afds" href="/docs/icse/Chemistry_Sample_Paper_1.doc" title="Sample Paper Chemistry - 1">Sample Paper Chemistry - 1</a></li>
                        </ul>
                </div>
                <h3>Biology</h3>
                <div class="papers">
                        <ul>
                            <li><a class="afds" href="/docs/icse/Biology_Sample_Paper_1.doc" title="Sample Paper Biology - 1">Sample Paper Biology - 1</a></li>
                        </ul>
                </div>
                <h3>History & Civics </h3>
                <div class="papers">
                        <ul>
                            <li><a class="afds" href="/docs/icse/History_Civics_Sample_Paper_1).doc" title="Sample paper History & Civics - 1">Sample Paper History & Civics</a></li>
                        </ul>
                </div>
        </div>
    <div class="col-xs-12 col-md-6">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad-vertical.php'; ?>
    </div>


</div>