<?php $this->headTitle()->set('ISC Previous Years\' Papers');
echo $this->headTitle();
$iscsp = $this->baseUrl('/isc/sample-papers');
$isccp = $this->baseUrl('/isc/isc-computer-practical');
$iscvv = $this->baseUrl('/isc/viva-voce');
$iscpro = $this->baseUrl('/isc/computer-project');
?>
<div class="resources">
    <h1>ISC Previous Years Papers</h1><hr />
    <div class="paperList">
        <h3>Computer Science</h3>
        <div class="papers">
            <ul>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/isc/ISC_2005.doc'); ?>" title="ISC Computer Science 2005 (Theory)">ISC 2005</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/isc/ISC_2006.doc'); ?>" title="ISC Computer Science 2006 (Theory)">ISC 2006</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/isc/ISC_2007.doc'); ?>" title="ISC Computer Science 2007 (Theory)">ISC 2007</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/isc/ISC_2008.doc'); ?>" title="ISC Computer Science 2008 (Theory)">ISC 2008</a></li>
                <li><a class="afds" href="<?php echo $this->baseUrl('/docs/isc/ISC_2009.doc'); ?>" title="ISC Computer Science 2009 (Theory)">ISC 2009</a></li>
            </ul>
        </div>
        <hr />
        <div>
            <h3>Other Resources:</h3>
            <div class="papers">
                <ul>
                    <li><a href="<?php echo $iscsp; ?>">ISC Sample Papers</a></li>
                    <li><a href="<?php echo $isccp; ?>">ISC Computer Practical</a></li>
                    <li><a href="<?php echo $iscvv; ?>">ISC Viva-Voce</a></li>
                    <li><a href="<?php echo $iscpro; ?>">ISC Computer Project</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="google-ad">
        <?php include APPLICATION_PATH.'/../layouts/templates/ads/google-ad-horizontal.php'; ?>
    </div>

</div>