<?php $this->headTitle()->set('Function Overloading in Java');
echo $this->headTitle();
?>
<div class="col-md-offset-1 programming topicsList" xmlns="http://www.w3.org/1999/html">
    <h1 class="text-center">Function(method) Overloading</h1><hr />
    <div class="content">
            <p> <b>Function(method) Overloading</b> is the Polymorphic behaviour of OOP( Objected Oriented Programming).
            When several functions(methods) with same name but different function signature are defined,
            the process is said to be <b>function(method) overloading</b>.<br />
            The functions(methods) defined herewith are referred to as <i><b>overloaded functions(methods)</b></i>.</p>
          <br />
        <p> The example below shows an overloaded function named <b>func</b>.</p>

       <pre class="code_snippet">

                public void func(int a)
                {
                //function body
                }
                public void func(float a)
                {
                //function body
                }
                public void func(String s1, String s2)
                {
                //function body
                }
        </pre>
    </div>
</div>