<div class="content">
<h2>Forum</h2>
	<table class="forum">

<thead>
	<tr><td class="category_heading" colspan="4">General Discussion</td></tr>
	<tr><th id="sno">Sno</th><th id="topics">Category</th><th id="posts">Posts</th>
		<th id="last_post">Last Post</th><!--<th id="created_by">Created By</th>--></tr>
</thead>

<tbody>
	<tr>
			<td>1</td>
			<td class="topics">Read Me</td>
			<td>15</td>
			<td class="last_post">Yesterday at 19:15pm by mansoorKing</td>
		</tr>

</tbody>
	</table>
	<table class="forum">

<thead>
	<tr><td class="category_heading" colspan="4">Subjects</td></tr>
	<tr><th id="sno">Sno</th><th id="topics">Category</th><th id="posts">Posts</th>
	<th id="last_post">Last Post</th><!--<th id="created_by">Created By</th>-->
	</tr>
</thead>

<tbody>
	<tr>
			<td>1</td>
			<td class="topics">Physics</td>
			<td>15</td>
			<td class="last_post">Yesterday at 19:15pm by mansoorKing</td>
		</tr>
	<tr>
			<td>1</td>
			<td class="topics">Chemistry</td>
			<td>15</td>
			<td class="last_post">Yesterday at 19:15pm by mansoorKing</td>
		</tr>
	<tr>
			<td>1</td>
			<td class="topics">Mathematics</td>
			<td>15</td>
			<td class="last_post">Yesterday at 19:15pm by mansoorKing</td>
		</tr>
	<tr>
			<td>1</td>
			<td class="topics">Computers</td>
			<td>15</td>
			<td class="last_post">Yesterday at 19:15pm by mansoorKing</td>
		</tr>
	<tr>
			<td>1</td>
			<td class="topics">English</td>
			<td>15</td>
			<td class="last_post">Yesterday at 19:15pm by mansoorKing</td>
		</tr>

</tbody>
	</table>

<table id="table_footer">
		<tfoot>
	<tr></tr>
	<tr>
		<th colspan="2">Rules and Guidelines</th>
	</tr>
	<tr><td colspan="4"><ol>
<li>Please do a quick search before posting new topics.</li>
<li>Try to help others by sharing your knowledge.</li>
<li>Refrain from posting comments not related to topic.</li>
<li>Choose your content/language carefully. Profanity of any sort will not be tolerated. You will be banned from the forum if your content is found objectionable.</li>
</ol></td></tr>
</tfoot>

	</table>
</div>
