<?php $this->headTitle()->set('Fun Facts');
echo $this->headTitle();
?>
<link  href="<?php echo $this->baseUrl();?>/skins/reds/css/quiz.css" media="screen" rel="stylesheet" type="text/css" >

<div id="main" class="col-sm-7 col-lg-9">
    <div class="content">
        <h1 class="text-center">Fun Facts</h1><hr />
        <?php if($this->paginator):?>
        <div class="facts-cont">
            <div class="clearfix">
                <?php $ctr = 1; $alpha = 0; $beta = 1; $gamma = 2; ?>
                <div class="col-sm-4 col-md-4 col-lg-4 alpha">
                    <?php $funFact = $this->paginator;?>
                    <?php $c=0; foreach($funFact as $key => $record):?>
                        <?php if($c == $alpha):?>
                            <div class="facts bc<?php echo $ctr;?>"><?php echo $record->fact;?></div>
                        <?php $alpha = $alpha + 3; $ctr ++; $ctr = $ctr > 20?1:$ctr; endif; ?>
                    <?php $c++; endforeach; ?>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 beta">
                    <?php $c=0; $funFact = $this->paginator;?>
                    <?php foreach($funFact as $key => $record):?>
                        <?php if($c == $beta):?>
                            <div class="facts bc<?php echo $ctr;?>"><?php echo $record->fact;?></div>
                        <?php $beta = $beta + 3;  $ctr ++; $ctr = $ctr > 20?1:$ctr; endif; ?>
                    <?php $c++; endforeach; ?>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4 alpha">
                    <?php $c=0; foreach($funFact as $key => $record):?>
                        <?php if($c == $gamma):?>
                            <div class="facts bc<?php echo $ctr;?>"><?php echo $record->fact;?></div>
                        <?php $gamma = $gamma + 3;  $ctr ++; $ctr = $ctr > 20?1:$ctr; endif; ?>
                    <?php $c++; endforeach; ?>
                </div>
            </div>
            <hr />
            <div id="pagination" class="pagination">
                <div class="controls">
                    <?php		echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'includes/paginationcontrol2.phtml');
                    ?>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<div class="col-sm-5 col-lg-3" id="sidebar_right">
    <fieldset class="home_right text-center google-ad">
        <?php include APPLICATION_PATH.'/../layouts/templates/google-ad.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <?php require_once APPLICATION_PATH.'/../layouts/templates/qotd.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <!--            --><?php //require_once APPLICATION_PATH.'/../layouts/templates/gplus.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <!--            --><?php //require_once APPLICATION_PATH.'/../layouts/templates/fb.php'; ?>
    </fieldset>
    <fieldset class="home_right text-center">
        <?php include_once APPLICATION_PATH.'/../layouts/templates/quick-links.php'; ?>
    </fieldset>
</div>
