<?php
    $forgotpwd   = $this->baseUrl('/user/password-recovery');
    $register    = $this->baseUrl('/register');
    $loginAction = $this->baseUrl('login');
?>
<div class="cont-mixed clearfix">
    <div class="sessions login">
        <div id="openid-login-cont">
            <div class="login">
                <div class="openid-login">
                    <p class="processing hide">Please wait...
                        <img src="<?php echo $this->baseUrl(); ?>/images/loading-s.gif" alt="Processing..." title="Processing..." />
                    </p>
                    <div class="clearfix">
                        <a id="fb-login" class="login-button col-xs-12" href="javascript:void(0);">
                            <img src="<?php echo $this->baseUrl(); ?>/images/fb-login.png" />
                        </a>
                        <a id="gmail-login" class="g-signin login-button col-xs-12" href="javascript:void(0);">
                            <img src="<?php echo $this->baseUrl(); ?>/images/gmail-login.png" />
                        </a>
                    </div>
                </div>
                <div class="login_or">
                    <hr />
                    <span class="span_or">OR</span>
                </div>
                <form action="<?php echo $loginAction; ?>" class="form" role="form" method="POST" enctype="application/x-www-form-urlencoded">
                    <?php if(isset($this->loginMessage)):?>
                        <div class="alert alert-danger">
                            <p><?php echo $this->loginMessage; ?></p>
                        </div>
                    <?php endif; ?>
                    <div class="_top-form">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                            <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                        </div>

                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group fpwd">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Remember me
                                </label>
                            </div>
                        <a class="pull-right" href="<?php echo $forgotpwd; ?>">Forgot Password?</a>
                    </div>
                    <div class="form-group">
                            <input type="submit" class="btn btn-primary btn-block" value="Sign in" />
                    </div>
                </form>
            </div>
            <div class="buttons">
                Dont't have an account? <a class="" href="<?php echo $register; ?>">Sign Up</a>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="usernameModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="bg-danger alert field-error hide">
                    <p></p>
                </div>
                <div class="bg-success field-success alert hide">
                    <p>Success! Please wait while you are redirected to your profile page...</p>
                </div>
                <div class="form-group regular">
                    <label for="username" class="control-label">Choose a username for your account: </label>
                    <input class="form-control" type="text" name="username" id="username" value="" />
                </div>
                <div class="form-group regular">
                    <label for="password" class="control-label">Password: </label>
                    <input class="form-control" type="password" name="password" id="up1" value="" />
                </div>
                <div class="form-group regular">
                    <label for="password1" class="control-label">Confirm Password: </label>
                    <input class="form-control" type="password" name="password1" id="up2" value="" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="submit-username">Submit</button>
            </div>
        </div>
    </div>
</div>

<script>
    var APP_ID = '<?php echo $this->APP_ID; ?>';
    var GOOGLE_CLIENT_ID = '<?php echo $this->GOOGLE_CLIENT_ID; ?>';
    var GOOGLE_API_KEY = '<?php echo $this->GOOGLE_API_KEY; ?>';
    var baseUrl = '<?php echo BASE_URL; ?>';
</script>
<script src="https://apis.google.com/js/client:plusone.js" type="text/javascript"></script>
<!--<script src="--><?php //echo $this->baseUrl('/scripts/index.js'); ?><!--"></script>-->