<div class="content sessions fpwd">
	<h2 class="text-center">Forgot your Password?</h2><hr />
	<?php
	if($this->success==1){?>
	<div class="error">
	<p>An email has been sent to your email account. Click on the activation link to reset your password.</p>
	</div>
	<?php }else{?>
	<p>Please provide the email you used to register on <a href="http://www.wethementors.com">www.wethementors.com</a>
	to initiate password recovery.</p><br />
		<?php if(isset($this->error)): ?>
            <div class="alert alert-danger">
                <p>
                    <?php echo $this->error; ?>
                </p>
            </div>
        <?php endif; ?>
	<?php
	    echo $this->form;
	}
	?>
</div>

	