<?php  $url=$this->url(array('controller'=>'user', 'action'=>'login')); ?>
    <div class="content center50">
    <h1>Reset password</h1><hr />
        <?php if(isset($this->errors)):?>
            <div class="alert alert-danger">
                <?php echo "<p>".$this->errors."</p>";?>
            </div>
        <?php endif; ?>

        <?php if($this->updated==1): ?>
            <p class="text-center">Your password has been reset. Click <a href="<?php echo $url;?>">here</a> to login to your account.</p>
        <?php else:
            echo $this->form;
        endif; ?>
</div>