<?php
	$this->headTitle()->set('Add guess question - ISC Computer Practical');
	echo $this->headTitle();
?>
<?php
	$list=$this->url(array('controller'=>'programs','action'=>'list-guess-questions'),null,true);
?>
<div class="fcgq">
    <div class="clearfix">
        <h1 class="pull-left">Add Practical/Guess Questions</h1>
        <a href="<?php echo $list; ?>" class="btn btn-sm btn-primary pull-right">List Questions</a>
    </div>
    <hr />
    <form class="form-horizontal" role="form" method="post" action="<?php echo $this->baseUrl().'/programs/add-guess-question'; ?>">
        <div class="form-group">
            <label for="year" class="col-sm-2 control-label">Choose year</label>
            <div class="col-sm-10">
                <select name="year" id="year" class="form-control">
                    <?php for($i=2000; $i<=date('Y'); $i++): ?>
                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="type" class="col-sm-2 control-label">Choose type</label>
            <div class="col-sm-10">
                <select name="type" id="type" class="form-control">
                    <option value="guess">Guess</option>
                    <option value="practical">Practical</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="question" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
                <textarea rows="5" class="form-control" placeholder="Add Question" name="question" id="question"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="solution" class="col-sm-2 control-label">Solution</label>
            <div class="col-sm-10">
                <textarea rows="12" class="form-control" placeholder="Add Question" name="solution" id="solution"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="submit" name="submit" class="btn btn-primary" value="Submit" />
            </div>
        </div>
    </form>
</div>