<div id="main" class="col-sm-12">
    <div class="content">

    <?php $add=$this->url(array('controller'=>'programs', 'action'=>'add'));  ?>
    <h1>Programs list</h1>
        <a href="<?php echo $add; ?>" class="btn btn-primary pull-right">Add more questions</a><br />
    <?php
        if($this->programs!=null){
            $i=0;
    ?>
        <table class="table table-responsive table-striped table-hover table-list">
            <tr>
                <th>Sl no</th>
                <th>Topic Name</th>
                <th>Question</th>
                <th>Solution</th>
                <th>Action</th>
            </tr>
        <?php
            foreach($this->programs as $program){
                $i++;
                ?>

                <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo $program->topic; ?></td>
                    <td><?php echo substr($program->question,0,200); ?></td>
                    <td><?php echo substr($program->solution,0,200); ?></td>
                    <?php
                    $delete=$this->url(array('controller'=>'programs', 'action'=>'delete','id'=>$program->sno));
                    $update=$this->url(array('controller'=>'programs', 'action'=>'update','id'=>$program->sno));
                    ?>
                    <td>
                        <a class="btn btn-xs btn-danger btn-block" href="<?php echo $delete; ?>">Delete</a>
                        <a class="btn btn-xs btn-info btn-block" href="<?php echo $update; ?>">Update</a>
                    </td>
                </tr>
        <?php
            }
        ?>
        </table>

        <?php
        }else{
            $add=$this->url(array('controller'=>'programs', 'action'=>'add'));

            ?>
            <p>You do not have any programs yet. <a href="<?php echo $add; ?>">Add one now</a></p>
        <?php } ?>
    </div>
</div>