<?php $this->headTitle()->set('List - Quotes');
echo $this->headTitle();
?>
<?php
    $add=$this->url(array('controller'=>'quotes', 'action'=>'add'));
    $update=$this->url(array('controller'=>'quotes', 'action'=>'update'));
?>
<div id="main" class="col-sm-12">
    <div class="content">
        <div class="clearfix">
            <h1 class="pull-left">Quotes list</h1>
            <a class="btn btn-primary pull-right" href="<?php echo $add; ?>">Add quote</a>
        </div>
        <hr />
        <?php
        if($this->paginator):
            $i=($this->currentPage * $this->recordsPerPage +1) - $this->recordsPerPage ;
            ?>
            <table class="table table-responsive table-striped table-hover table-list quotes-list">
                <tr>
                    <th>Sno</th>
                    <th>Quote</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                <?php
                foreach($this->paginator as $quote):?>

                    <tr>
                        <td><?php echo $i; ?></td>
                        <td><?php echo $quote->quote; ?> - <?php echo $quote->quote_by; ?> </td>
                        <td><?php echo $quote->created; ?></td>
                        <td colspan="2">
                            <a class="btn btn-xs btn-danger delete-quote" href="#">Delete</a>
                            <input type="hidden" name="id" value="<?php echo $quote->id; ?>" />
                            <a class="btn btn-xs btn-info update-quote" href="<?php echo $update.'/id/'.$quote->id;?>">Update</a>
                        </td>
                    </tr>

                    <?php
                    $i++;
                endforeach;
                ?>
            </table>
            <div id="pagination" class="pagination">
                <div class="controls">
                    <?php
                        echo $this->paginationControl($this->paginator,
                        'Sliding',
                        'includes/paginationcontrol2.phtml');
                    ?>
                </div>
            </div>
            <?php	endif;	?>
    </div>
</div>