<?php
    $this->headTitle()->set('Update - Quote');
    echo $this->headTitle();
    $list=$this->url(array('controller'=>'quotes','action'=>'list'),null,true);
?>
<div class="content">
    <div class="fcgq">
        <div class="clearfix">
            <h1 class="pull-left">Update Quote</h1>
            <a href="<?php echo $list; ?>" class="btn btn-sm btn-primary pull-right">List Quotes</a>
        </div>
        <hr />
        <div class="admin-form-center">
            <?php if($this->record == -1): ?>
            <div class="alert alert-danger">
                <p>Record not found!</p>
            </div>
            <?php else: ?>
            <div class="alert alert-danger hide">
                <p>Something went wrong. Please try again later.</p>
            </div>
            <div class="alert alert-success hide">
                <p>Record updated successfully.</p>
            </div>
            <form role="form" action="#" id="update-quote">
                <div class="form-group">
                    <label for="quote">Quote</label>
                    <textarea rows="5" class="form-control" id="quote" placeholder="Quote"><?php echo $this->record->quote; ?></textarea>
                </div>
                <div class="form-group">
                    <label for="author">Author</label>
                    <input class="form-control" id="author" placeholder="Author" value="<?php echo $this->record->quote_by; ?>" />
                </div>
                <input type="hidden" name="id" value="<?php echo $this->record->id; ?>" />
                <button class="btn btn-primary">Update</button>
                <span class="loading hide">Please wait ...
                    <img src="<?php echo $this->baseUrl(); ?>/images/loading-s.gif" alt="loading" />
                </span>
            </form>
            <?php endif; ?>
        </div>
    </div>
</div>