<?php
$this->headTitle()->set('Add Quote');
echo $this->headTitle();
?>

<div class="content">
	<div class="list-head">
		<h2>Add Quote</h2>
	</div>
	<div id="add_quiz" class="form_short">
        <div class="alert alert-danger hide">
            <p>Something went wrong. Please try again later.</p>
        </div>
        <div class="alert alert-success hide">
            <p>Record added successfully.</p>
        </div>
        <form role="form" action="javascript:void(0);" id="add-quote-form">
            <div class="form-group">
                <label for="quote">Quote</label>
                <textarea rows="5" class="form-control" name="quote" id="quote" placeholder="Quote"></textarea>
            </div>
            <div class="form-group">
                <label for="author">Author</label>
                <input class="form-control" id="author" name="author" placeholder="Author" />
            </div>
            <div class="form-group">
                <label for="visible">Visible</label>
	            <select class="form-control" id="visible" name="visible">
		            <option label="Yes" value="1">Yes</option>
		            <option label="No" value="0">No</option>
	            </select>
            </div>
            <button class="btn btn-primary">Submit</button>
            <span class="loading hide">Please wait ...
                <img src="<?php echo $this->baseUrl('/images/loading-s.gif'); ?>" alt="loading" />
            </span>

        </form>
    </div>

</div>
