<?php
$this->headTitle()->set('Create Note Category');
echo $this->headTitle();
?>
<div class="content">
	<div class="list-head">
		<h2>Create Note Category</h2>
	</div>
	<div class="form_short">
		<?php if(isset($this->msg)): ?>
			<div class="alert alert-info">
				<p><?php  echo $this->msg; ?></p>
			</div>
		<?php endif; ?>

		<form class="form-horizontal" role="form" method="post" action="<?php echo $this->baseUrl().'/admin/create-notes-category'; ?>">
			<div class="form-group">
				<label for="question" class="col-sm-2 control-label">Category</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" placeholder="Add Notes Category" name="category" id="category" />
				</div>
			</div>
			<div class="form-group">
				<label for="question" class="col-sm-2 control-label">Type</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" placeholder="Add Notes Category Type" name="type" id="type" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-10 col-sm-offset-2">
					<input type="submit" name="submit" class="btn btn-primary" value="Submit" />
				</div>
			</div>
		</form>
	</div>
</div>