<?php
$this->headTitle()->set('Create Notes SubCategory');
echo $this->headTitle();
?>
<div class="content">
	<div class="list-head">
		<h2>Create Notes SubCategory</h2>
	</div>
	<div class="form_short">
		<?php if(isset($this->msg)): ?>
			<div class="alert alert-info">
				<p><?php  echo $this->msg; ?></p>
			</div>
		<?php endif; ?>

		<form class="form-horizontal" role="form" method="post" action="<?php echo $this->baseUrl().'/admin/create-notes-sub-category'; ?>">
			<div class="form-group">
				<label for="category" class="col-sm-2 control-label">Category</label>
				<div class="col-sm-10">
					<select name="category" id="category" class="form-control">
						<?php foreach($this->category as $category): ?>
							<option value="<?php echo $category->id; ?>"><?php echo $category->category; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="sub_category" class="col-sm-2 control-label">SubCategory</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" placeholder="Add Notes Category" name="sub_category" id="sub_category" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-10 col-sm-offset-2">
					<input type="submit" name="submit" class="btn btn-primary" value="Submit" />
				</div>
			</div>
		</form>
	</div>
</div>