<?php
$this->headTitle()->set('Add Video');
echo $this->headTitle();
?>

<div class="content">
    <div class="list-head">
        <h2>Add Video</h2>
    </div>
    <div class="form_short">
        <?php if(isset($this->success)):?>
            <div class="alert alert-success">
	            <p>
		            <?php echo $this->success;?>
	            </p>
            </div>
        <?php endif; ?>
        <?php echo $this->form;?>
    </div>
</div>