<?php
	$this->headTitle()->set('Notes Content List');
	echo $this->headTitle();
	$create = $this->url(array('controller' => 'admin', 'action' => 'create-notes-content'));
?>

<div class="content">

	<div class="list-head clearfix">
		<h2>Notes Content List - <small><?php echo empty($this->pageRange)?0:$this->pageRange; ?> Records</small></h2>
		<div class="sort">
			<div class="dropdown">
				<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					Sort By
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					<?php foreach($this->notes as $category): ?>
						<li>
							<a href="<?php echo $this->baseUrl('/admin/read-notes-content?sub_category='.urlencode($category['sub_category'])); ?>">
								<?php echo $category['sub_category']; ?>
							</a></li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
		<a href="<?php echo $create; ?>" class="btn btn-success pull-right">
			<i class="glyphicon glyphicon-plus"></i>
				Create Notes Content
		</a>
	</div>
	<?php if($this->paginator): ?>
		<table class="table table-bordered table-responsive table-striped notes">
			<thead>
				<tr>
					<th>#</th>
					<th>Category</th>
					<th>Sub Category</th>
					<th>Heading</th>
					<th>Slug</th>
					<th>Cover Image</th>
					<th>Content</th>
					<th>Extract</th>
					<th>Created</th>
					<th>Updated</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = ($this->currentPage - 1) * $this->limit; ?>
				<?php foreach($this->paginator as $note): ?>
					<tr>
						<td><?php echo ++$i; ?></td>
						<td><?php echo ucwords($note->category); ?></td>
						<td><?php echo ucwords($note->sub_category); ?></td>
						<td><?php echo $note->heading; ?></td>
						<td><?php echo $note->slug; ?></td>
						<td>
							<div style="background-image: url('/images/content/uploads/<?php echo $note->cover_image; ?>'); background-size: cover; height: 100px; width: 200px; "></div>

						</td>
						<td><?php echo htmlentities(substr($note->content,0,200)); ?></td>
						<td><?php echo substr($note->extract, 0, 100); ?></td>
						<td><?php echo $note->created; ?></td>
						<td><?php echo $note->updated; ?></td>
						<?php
							$update=$this->url(array('controller'=>'admin', 'action'=>'update-notes-content','id'=>$note->id));
						?>
						<td>
							<input type="hidden" value="<?php echo $note->id; ?>" />
							<a class="btn btn-xs btn-block btn-danger delete-notes-content" href="javascript:void(0);">Delete</a>
							<a class="btn btn-xs btn-info btn-block" href="<?php echo $update; ?>">Update</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<div id="pagination" class="pagination">
			<?php echo $this->paginationControl($this->paginator,
				'Elastic',
				'includes/paginationcontrol.phtml');
			?>
		</div>
	<?php endif; ?>

</div>