<?php
    $this->headTitle()->set('Java Quiz Participants List');
    echo $this->headTitle();
?>

<div class="content">
    <div class="list-head">
        <h2>Java Quiz Participants</h2>
    </div>
    <?php if($this->paginator) { ?>
        <table class="table table-bordered table-striped">
            <thead>
		        <tr>
	                <th>Sno</th>
	                <th>Username</th>
	                <th>Category</th>
	                <th>Score</th>
	                <th>Attempts</th>
	                <th>Date</th>
	            </tr>
            </thead>
	        <tbody>
		        <?php $i = ($this->currentPage - 1) * $this->limit; ?>
	            <?php foreach ($this->paginator as $user): ?>
	                <tr>
	                    <td><?php echo ++$i; ?></td>
	                    <td><?php echo $user->username; ?></td>
	                    <td><?php echo $user->category; ?></td>
	                    <td><?php echo $user->score; ?></td>
	                    <td><?php echo $user->attempts; ?></td>
	                    <td><?php echo $user->created; ?></td>
	                </tr>
	            <?php endforeach; ?>
	        </tbody>
        </table>
        <div id="pagination" class="pagination">
            <?php echo $this->paginationControl($this->paginator,
                'Jumping',
                'includes/paginationcontrol.phtml');
            ?>
        </div>
    <?php } ?>

</div>
