<?php
	$this->headTitle()->set('Topics List');
	echo $this->headTitle();
	$create = $this->url(array('controller'=>'admin', 'action'=>'create-topic'));

?>

<div class="content">

	<div class="list-head clearfix">
		<h2>Topics List</h2>
		<a href="<?php echo $create; ?>" class="btn btn-success pull-right">
			<i class="glyphicon glyphicon-plus"></i>
			Create Topic
		</a>
	</div>
	<?php if($this->paginator): ?>
		<table class="table table-bordered table-striped topics">
			<thead>
				<tr>
					<th>Sl no</th>
					<th>Name</th>
					<th>URL Name</th>
					<th>Created</th>
					<th>Visible?</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = ($this->currentPage - 1) * $this->limit; ?>
				<?php foreach($this->paginator as $topic): ?>
					<tr>
						<td><?php echo ++$i; ?></td>
						<td><?php echo $topic->topic; ?></td>
						<td><?php echo $topic->url_name; ?></td>
						<td><?php echo $topic->created; ?></td>
						<td>
							<?php if($topic->visible):?>
								<span class="label label-success">TRUE</span>
							<?php else: ?>
								<span class="label label-danger">FALSE</span>
							<?php endif; ?>
						</td>
						<?php $update = $this->url(array('controller'=>'admin', 'action'=>'update-topic','id'=> $topic->id)); ?>
						<td>
							<a class="btn btn-xs btn-danger delete-subject" href="javascript:void(0);">Delete</a>
							<input type="hidden" value="<?php echo $topic->id; ?>" />
							<a class="btn btn-xs btn-info"  href="<?php echo $update; ?>">Update</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<div id="pagination" class="pagination">
			<?php echo $this->paginationControl($this->paginator,
				'Elastic',
				'includes/paginationcontrol.phtml');
			?>
		</div>
	<?php endif; ?>

</div>