<?php
    $this->headTitle()->set('Annual Exam Questions List');
    echo $this->headTitle();
	$create = $this->baseUrl('/admin/create-yearly-question');
?>


<div class="content">

    <div class="list-head clearfix">
        <h3>Annual Exam Questions List - <strong><?php echo $this->totalCount; ?> Questions</strong></h3>
	    <a href="<?php echo $create; ?>" class="btn btn-success pull-right">
		    <span class="glyphicon glyphicon-plus"></span>
		    Add Annual Exam Questions
	    </a>
    </div>
	<h4>TODO: Add sort by year and type filters</h4>
    <?php if($this->paginator): ?>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Subject</th>
                <th>Year</th>
                <th>Type</th>
                <th>Position</th>
                <th>Tags</th>
	            <th>Slug</th>
                <th>Heading</th>
                <th>Question</th>
                <th>Solution</th>
                <th>Visible</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php $i = ($this->currentPage - 1) * $this->limit; ?>
            <?php foreach($this->paginator as $record): ?>
                <tr>
                    <td><?php echo ++$i; ?></td>
                    <td><?php echo $record['subject']; ?></td>
                    <td><?php echo $record['year']; ?></td>
                    <td><?php echo $record['type']; ?></td>
                    <td><?php echo $record['position']; ?></td>
                    <td>
	                    <?php
	                        if(!empty($record['topics'])):
		                        $labelColor = array('info','success','danger','default','primary');
		                        foreach ($record['topics'] as $topic):
                        ?>
	                        <span class="label label-<?php echo $labelColor[array_rand($labelColor)]; ?>"><?php echo $topic['url_name']; ?></span>
                        <?php
	                        endforeach;
	                        endif;
	                    ?>
                    </td>
	                <td><?php echo $record['slug']; ?></td>
	                <td><?php echo $record['heading']; ?></td>
                    <td><?php echo htmlentities(substr($record['question'],0,100)); ?></td>
                    <td><?php echo htmlentities(substr($record['solution'],0,100)); ?></td>
                    <td>
	                    <?php if($record['visible']):?>
		                    <span class="label label-success">TRUE</span>
	                    <?php else: ?>
		                    <span class="label label-danger">FALSE</span>
	                    <?php endif; ?>
                    </td>
                    <?php
	                    $delete = $this->url(array('controller'=>'admin', 'action'=>'delete-yearly-question','id'=> $record['id']));
	                    $update = $this->url(array('controller'=>'admin', 'action'=>'update-yearly-question','id'=> $record['id']));
                    ?>
                    <td>
                        <a class="btn btn-xs btn-danger btn-block" href="<?php echo $delete; ?>">Delete</a>
                        <a class="btn btn-xs btn-info btn-block" href="<?php echo $update; ?>">Update</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div id="pagination" class="pagination">
            <?php echo $this->paginationControl($this->paginator,
                'Elastic',
                'includes/paginationcontrol.phtml');
            ?>
        </div>
    <?php endif; ?>

</div>