<?php
	$this->headTitle()->set('Update Topic');
	echo $this->headTitle();
	$list = $this->baseUrl('/admin/read-topics');
?>
<div class="content">
	<div class="list-head">
		<h2>Update Topic</h2>
		<a href="<?php echo $list; ?>" class="btn btn-success pull-right">
			<i class="glyphicon glyphicon-list"></i>
			List Topics
		</a>
	</div>
	<div class="form_short">
		<div class="alert alert-danger hide">
			<p>Something went wrong. Please try again later.</p>
		</div>
		<div class="alert alert-success hide">
			<p>Record updated successfully.</p>
		</div>

		<form class="form-horizontal" role="form" method="post" action="javascript:void(0);">
			<div class="form-group">
				<label for="topic" class="col-sm-2 control-label">Name</label>
				<div class="col-sm-10">
					<input type="text" value="<?php echo $this->record->topic;?>" class="form-control" placeholder="Topic Name" name="topic" id="topic" />
				</div>
			</div>
			<div class="form-group">
				<label for="url_name" class="col-sm-2 control-label">URL Name</label>
				<div class="col-sm-10">
					<input type="text" value="<?php echo $this->record->url_name;?>" class="form-control" placeholder="URL Name" name="url_name" id="url_name" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-10 col-sm-offset-1">
					<label for="visible" class="control-label">
						Visible
						<input type="checkbox" name="visible" id="visible" <?php echo $this->record->visible == 1? "checked":""; ?> aria-label="...">
					</label>
				</div>
			</div>
			<input type="hidden" name="id" value="<?php echo $this->record->id; ?>" />
			<button class="btn btn-primary col-sm-offset-2" onclick="updateTopic(this);">Update</button>
            <span class="loading hide">Please wait ...
                <img src="<?php echo $this->baseUrl(); ?>/images/loading-s.gif" alt="loading" />
            </span>
		</form>
	</div>
</div>