<?php
	$this->headTitle()->set('Update Note Category');
	echo $this->headTitle();
	$list = $this->baseUrl('/admin/read-notes-category');
?>
<div class="content">
	<div class="list-head">
		<h2>Update Note Category</h2>
		<a href="<?php echo $list; ?>" class="btn btn-success pull-right">
			<i class="glyphicon glyphicon-list"></i>
			List Notes Category
		</a>
	</div>
	<div class="form_short">
		<div class="alert alert-danger hide">
			<p>Something went wrong. Please try again later.</p>
		</div>
		<div class="alert alert-success hide">
			<p>Record updated successfully.</p>
		</div>

		<form class="form-horizontal" role="form" method="post" action="javascript:void(0);">
			<div class="form-group">
				<label for="question" class="col-sm-2 control-label">Category</label>
				<div class="col-sm-10">
					<input type="text" value="<?php echo $this->record->category;?>" class="form-control" placeholder="Notes Category" name="category" id="category" />
				</div>
			</div>
			<div class="form-group">
				<label for="question" class="col-sm-2 control-label">Type</label>
				<div class="col-sm-10">
					<input type="text" value="<?php echo $this->record->type;?>" class="form-control" placeholder="Notes Category Type" name="type" id="type" />
				</div>
			</div>
			<input type="hidden" name="id" value="<?php echo $this->record->id; ?>" />
			<button class="btn btn-primary col-sm-offset-2" onclick="updateNotesCategory(this);">Update</button>
            <span class="loading hide">Please wait ...
                <img src="<?php echo $this->baseUrl(); ?>/images/loading-s.gif" alt="loading" />
            </span>
		</form>
	</div>
</div>