<?php
	$this->headTitle()->set('Update Note');
	echo $this->headTitle();
	$list = $this->baseUrl('/admin/read-notes');
?>

<div class="content">
	<div class="list-head">
		<h2>Update Note</h2>
		<a href="<?php echo $list; ?>" class="btn btn-success pull-right">
			<i class="glyphicon glyphicon-list"></i>
			List Notes
		</a>
	</div>
	<div class="form_short stretch">

		<?php  if(isset($this->message)): ?>
			<div class="alert alert-info">
				<?php if(is_array($this->message)): ?>
					<ul>
						<?php foreach ($this->message as $message): ?>
							<li><?php echo $message; ?></li>
						<?php endforeach; ?>
					</ul>
				<?php else: ?>
					<p><?php echo $this->message; ?></p>
				<?php endif; ?>
			</div>
		<?php endif; ?>

		<?php $form = $this->form; ?>

		<form class="form-horizontal notes-form" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data">

			<div class="form-group">
				<?php echo $form->category->renderLabel() ?>
				<?php echo $form->category->renderViewHelper() ?>
			</div>

			<div class="form-group">
				<?php echo $form->sub_category->renderLabel() ?>
				<?php echo $form->sub_category->renderViewHelper() ?>
			</div>

			<div class="form-group">
				<?php echo $form->heading->renderLabel() ?>
				<?php echo $form->heading->renderViewHelper() ?>
			</div>

			<div class="form-group">
				<?php echo $form->slug->renderLabel() ?>
				<?php echo $form->slug->renderViewHelper() ?>
			</div>

			<div class="form-group">
				<?php echo $form->cover_image->renderLabel() ?>
				<?php echo $form->cover_image->renderFile(); ?>
				<div class="center-block" id="preview-image" style="background-image: url('/images/content/uploads/<?php echo $this->note->cover_image; ?>'); background-size: cover; height: 300px;background-position: center center; ">

				</div>
			</div>

			<div class="form-group">
				<?php echo $form->deleted->renderLabel() ?>
				<?php echo $form->deleted->renderViewHelper() ?>
			</div>

			<div class="form-group">
				<?php echo $form->submit->renderViewHelper() ?>
			</div>
			<?php echo $form->file_changed->renderViewHelper(); ?>
		</form>

	</div>

</div>