<?php
    $this->headTitle()->set('Update Quote');
    echo $this->headTitle();
?>

<div class="content">
	<div class="list-head">
		<h2>Update Quote</h2>
	</div>
	<div class="form_short">
        <?php if(empty($this->record)): ?>
	        <div class="alert alert-danger">
	            <p>Record not found!</p>
	        </div>
        <?php else: ?>
	        <div class="alert alert-danger hide">
	            <p>Something went wrong. Please try again later.</p>
	        </div>
	        <div class="alert alert-success hide">
	            <p>Record updated successfully.</p>
	        </div>
	        <form role="form" action="javascript:void(0);" id="update-quote-form">

		        <div class="form-group">
	                <label for="quote">Quote</label>
	                <textarea rows="5" class="form-control" name="quote" id="quote" placeholder="Quote"><?php echo $this->record->quote; ?></textarea>
	            </div>

	            <div class="form-group">
	                <label for="author">Author</label>
	                <input class="form-control" name="author" id="author" placeholder="Author" value="<?php echo $this->record->author; ?>" />
	            </div>
		        <div class="form-group">
			        <label for="visible">Visible</label>
			        <select class="form-control" id="visible" name="visible">
				        <option label="Yes" value="1">Yes</option>
				        <option label="No" value="0">No</option>
			        </select>
		        </div>

	            <input type="hidden" name="id" value="<?php echo $this->record->id; ?>" />
	            <button class="btn btn-primary">Update</button>
	            <span class="loading hide">Please wait ...
	                <img src="<?php echo $this->baseUrl('/images/loading-s.gif'); ?>" alt="loading..." />
	            </span>
	        </form>
        <?php endif; ?>
    </div>
</div>