<?php
	$this->headTitle()->set('Update Notes SubCategory');
	echo $this->headTitle();
	$list = $this->baseUrl('/admin/read-notes-sub-category');
?>
<div class="content">
	<div class="list-head">
		<h2>Update Notes SubCategory</h2>
		<a href="<?php echo $list; ?>" class="btn btn-success pull-right">
			<i class="glyphicon glyphicon-list"></i>
			List Notes SubCategory
		</a>
	</div>
	<div class="form_short">
		<div class="alert alert-danger hide">
			<p>Something went wrong. Please try again later.</p>
		</div>
		<div class="alert alert-success hide">
			<p>Record updated successfully.</p>
		</div>

		<form class="form-horizontal" role="form" method="post" action="javascript:void(0);">
			<div class="form-group">
				<label for="category_id" class="col-sm-2 control-label">Category</label>
				<div class="col-sm-10">
					<select name="category" id="category" class="form-control">
						<?php foreach($this->categories as $category): ?>
							<option value="<?php echo $category->id; ?>" <?php echo $category->id == $this->sub_category->category?'selected': ''; ?>><?php echo $category->category; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="sub_category" class="col-sm-2 control-label">SubCategory</label>
				<div class="col-sm-10">
					<input type="text" name="sub_category" id="sub_category" class="form-control" value="<?php echo $this->sub_category->sub_category; ?>">
				</div>
			</div>
			<input type="hidden" name="id" value="<?php echo $this->sub_category->id; ?>" />
			<button class="btn btn-primary col-sm-offset-2" onclick="updateNotesSubCategory(this);">Update</button>
            <span class="loading hide">Please wait ...
                <img src="<?php echo $this->baseUrl(); ?>/images/loading-s.gif" alt="loading" />
            </span>
		</form>
	</div>
</div>