<div class="content">

	<div class="homepage">

		<div class="col-sm-12 col-md-4 sbl">

			<div id="unit-list">
				<?php include_once APPLICATION_PATH.'/../layouts/templates/_sidebar-left-home.php'; ?>
			</div>
		</div>

		<div class="col-sm-12 col-md-8" id="unit-stream">

			<?php if(isset($this->paginator)): ?>
				<?php foreach ($this->paginator as $index => $note): ?>
					<?php
						$colors = array('danger','primary','success','info', 'warning');
						if($note['category'] == 'people'){
							$link = $this->baseUrl('people/'.$note['slug']);
						}else{
							$link = $this->baseUrl('notes/'.strtolower(str_replace(" ", "-", $note['category'])).'/'.$note['slug']);
						}
					?>

					<?php if($index == 5): ?>
						<div class="ad">
							<?php include_once APPLICATION_PATH.'/../layouts/templates/ads/gad-homestream.php'; ?>
						</div>
						<br />
					<?php endif; ?>

					<?php if($index == 11): ?>
						<div class="ad">
							<?php include_once APPLICATION_PATH.'/../layouts/templates/ads/amazon_affiliate.php'; ?>
						</div>
						<br />
					<?php endif; ?>

					<div class="qgroupc">
						<?php if(!empty($note['sub_category'])): ?>
							<div class="category btn-<?php echo $colors[array_rand($colors)]; ?>">
								<a href="<?php echo $this->baseUrl('notes/'.$note['notes_slug']); ?>"><?php echo ucwords($note['sub_category']) ?></a>
							</div>
						<?php endif; ?>
						<div class="page-header">
							<h1>
								<?php echo $note['heading']; ?>

								<?php if(isset($_SESSION['user']['admin']) && $_SESSION['user']['admin'] == true): ?>
									<a class="btn btn-primary btn-xs" href="<?php echo $this->baseUrl('/admin/update-notes-content/id/'.$note->id); ?>">Edit</a>
								<?php endif; ?>
							</h1>
						</div>
						<div class="qgroup">
							<?php if(!empty($note['cover_image'])): ?>
								<div class="unit_image">
									<img class="img-thumbnail" src="<?php echo $this->baseUrl('/images/content/uploads/'.$note['cover_image']); ?>" alt="<?php echo ucwords($note['heading']); ?> Notes" />
								</div>
							<?php endif; ?>
							<div class="unit_desc">
								<blockquote><?php echo strip_tags($note['extract']); ?></blockquote>
							</div>
						</div>
						<div class="center-block cbal">
							<a class="btn btn-sm btn-default" href="<?php echo $link; ?>">
								Read More
							</a>
						</div>
					</div>
				<?php endforeach; ?>
				<div id="pagination" class="pagination qgroupc">
					<?php echo $this->paginationControl($this->paginator,
						'Sliding',
						'includes/itemPagination.phtml');
					?>
				</div>
			<?php else: ?>
				<div class="alert alert-danger">
					<p>No result found!</p>
				</div>
			<?php endif; ?>

		</div>

	</div>

</div>
