<div class="content pptou">
<h1>Privacy Policy</h1>
<p>Any usage of the terms, &#039WE&#039, &#039OUR&#039, &#039US&#039, &#039SITE&#039 refers to the website wethementors.com. Wethementors.com reserve the right to modify the information contained herein at anytime without prior notice. If we do make changes to our privacy policies, we will modify this page accordingly. Check this page periodically for amendments. This site and all information and materials on it are provided to you "AS IS" without warranty of any kind.
YOUR USE OF THE SITE, OR YOUR PROVISION TO US OF ANY PERSONAL INFORMATION CONSTITUTES YOUR AGREEMENT TO THESE TERMS AND ANY SUBSEQUENT CHANGES TO THESE TERMS.
</p>
<h2>Normal Browsing</h2>
<p>As with many websites, we may collect certain information, even when you are not logged in.
    When you browse, read, or download information from the Site, data is collected by us,
    including but not limited to your IP address, URL request, browser type, and date and time of your request.
    However, we do not track information on which pages an individual user visits. We do not collect any other information without your knowledge and permission. We use this information to improve the usefulness of the site to our visitors. Unless a visitor affirmatively provide additional information to us, we do not collect or store personally identifiable information such as name, mailing address, email address, phone number, or social security number.
</p>
<h2>Information You Provide</h2>
<p>wethementors.com requests personally identifiable information when you register with us. Information may be used or requested to perform research,
    improve usability of the site, administer mailing lists or online communities, or other activities.
    This information may include, but is not limited to, personal names, e-mail addresses, location, and occupation.
</p>
<h2>Cookies </h2>
<p>Cookies are small text files that the site can send to your browser for storage on your computer's hard drive. They make your use of the site easier by saving your status and preferences and are refreshed every time you visit. We may use session cookies when you visit our website while your browser is open, or while you are logged into the site. To facilitate our registration and login functions, we may use cookies to recognize when you return to the site. If you do not logout of your account, these cookies allow us to keep track of your username and password so that you do not have to resubmit the information to log into your account. If others will be using your computer, you should log out of your account so that your logon information is cleared. Most browser are initially set to accept cookies, but you may be able to change the settings to refuse cookies or to be alerted when cookies are being sent.
</p>
<h2>Security </h2>
<p>Wethementors.com has security measures in place to protect the loss, misuse and alteration of the information under our control. However, your confidential use of the site cannot be guaranteed by us. Wethementors.com shall not be responsible for any harm that you or any person may suffer as a result of a breach of confidentiality in respect to your use of this site or any information you transmitted to the Site.
</p>
<h2>Registration</h2>
<p>wethementors.com collects demographic and profile data to provide customized experience to our users. We do not intend to follow &#039one size fits all&#039 approach, hence we strive to provide the best of services to all the registered users as per their trend of usage. 
</p>
<h2>Intimation</h2>
<p>wethementors.com intimate their registered users by email regarding the addition of new features on the website which includes tutorials, examination question papers, solved papers, instructional videos, quiz, games etc. We do not spam our users with bulk emails neither do we share the emails of our registered users with third parties. If any registered user wants to opt out of receiving messages he/she may contact us at contact@wethementors.com. 
</p>
<h2>Advertising and Third Party Links</h2>
<p>Advertisers and affiliate partners on wethementors.com may request information directly from users, or link to sites that do so. wethementors.com has no control over its advertisers' privacy policies, and encourages users to review such policies prior to submitting any personal information to them.
wethementors.com provides links to non-advertising websites as well and similarly has no control of either the content or privacy policies of such sites, nor should such links be considered an endorsement of these sites except where explicitly stated.
</p>
</div>